gerbera: Upgrade to 3.0.0
Add missing dependencies on icu and jsoncpp

Package bash-completion scripts, fixes

ERROR: gerbera-3.0.0-r0 do_package: QA Issue: gerbera: Files/directories were installed but not shipped in any package:
  /usr/share/bash-completion
  /usr/share/bash-completion/completions
  /usr/share/bash-completion/completions/gerbera

Signed-off-by: Khem Raj <raj.khem@gmail.com>