gflags: Fix fetch URL
Fixes:
ARNING: gflags-2.1.2-r0 do_fetch: Failed to fetch URL
git://github.com/gflags/gflags.git;branch=master, attempting MIRRORS if
available
ERROR: gflags-2.1.2-r0 do_fetch: Fetcher failure: Unable to find
revision 1a02f2851ee3d48d32d2c8f4d8f390a0bc25565c in branch master even
from upstream
ERROR: gflags-2.1.2-r0 do_fetch: Fetcher failure for URL:
'git://github.com/gflags/gflags.git;branch=master'. Unable to fetch URL
from any source

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 1ba2436bdd9f22070c7e0a00f3a7422f6ecdcc4e)
Signed-off-by: Armin Kuster <akuster808@gmail.com>