v4l-utils: added missing dependency on udev
Upgrading to newer v4l-utils 1.12.3 on commit f84a551f2d419df88b85987855fec866d9e84b4a
Is causing issues because libdvbv5 now require libudev in order to work
(commit db42484881bf5e6a902de51fe42444ddf286d52a on v4l-utils).

First issue is missing dvb utils dvb-fe-tool, dvb-format-convert, dvbv5-daemon, dvbv5-scan, dvbv5-zap
because libdvbv5 requires now libudev.

Another issue was the failure of building dvb-apps (currently removed from master)
because the v4l-utils-native is missing dvb-format-convert.

This commit adds the missing udev dependency only on target and brings back the missing dvb utils.

Adding udev on native build is not possible because nothing provides udev-native.

Additionally add lib pthread to LDFLAGS in order to solve building with gold.

../../lib/libdvbv5/.libs/libdvbv5.so: error: undefined reference to 'pthread_cancel'
../../lib/libdvbv5/.libs/libdvbv5.so: error: undefined reference to 'pthread_create'

Issue with gold linking reported upstream and hopefully will be addressed soon.

Signed-off-by: Athanasios Oikonomou <athoik@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>