python3-pyatspi: restrict with GTK2DISTROFEATURES
* fixes:
  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'gtk+' (but meta-oe/meta-python/recipes-devtools/python/python3-pyatspi_2.32.1.bb DEPENDS on or otherwise requires it)
  gtk+ was skipped: one of 'x11 directfb' needs to be in DISTRO_FEATURES
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-pyatspi', 'gtk+']

  Summary: There was 1 WARNING message shown.
  Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>