ldns: fix override syntax
Commit 2e794f33a43d71bb9861 cherry-picked a fix from master, which used
the new override syntax, which was introduced in poky commit
2abf8a699edd513405be (2021-07-25, "bitbake: bitbake: Switch to using new
override syntax"). However, this change was merged after 3.4_M2 and is
not part of hardknott, so bitbake complains about the new syntax:

    ERROR: ParseError at
    …/meta-openembedded/meta-oe/recipes-devtools/ldns/ldns_1.7.1.bb:20:
    unparsed line: 'do_install:append() {'

Revert to the old syntax on the hardknott branch for now.

Fixes: 2e794f33a43d71bb9861 (2021-08-09, "ldns: fix QA Issue after LDFLAGS change")
Signed-off-by: Roland Hieber <rhi@pengutronix.de>
Signed-off-by: Armin Kuster <akuster808@gmail.com>