iwd: Module load dir should be relative to root_dir
This is autodetected by configure from systemd.pc and it depends on
value of root_dir ( usrmerge ) and not /usr being hardcoded eg. in
nonarch_libdir this has been fixed in systemd [1]

Fixes
ERROR: iwd-1.8-r0 do_package: QA Issue: iwd: Files/directories were installed but not shipped in any package:
/lib/modules-load.d
/lib/modules-load.d/pkcs8.conf

[1] https://github.com/systemd/systemd/commit/4a56315a990b802860170ecd1bbd3eb68e14a38b

Signed-off-by: Khem Raj <raj.khem@gmail.com>