python3-parallax: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import parallax
 [snip]
 ModuleNotFoundError: No module named 'fcntl'
 ModuleNotFoundError: No module named 'Queue'
 ModuleNotFoundError: No module named 'getpass'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>