python3-pyudev: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pyudev
 [snip]
 ModuleNotFoundError: No module named 'fcntl'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>