[protobuf] Link with libatomic on mips
mips does not have compiler builtins for 64bit atomics

Fix:
/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/protobuf/5.29.4/recipe-sysroot/usr/lib/libabsl_spinlock_wait.so.2501.0.0: undefined reference to `__atomic_store_8'