augeas: Upgrade to 1.10.1
* Add EXTRA_AUTORECONF += "-I ${S}/gnulib/m4" to
  fix below compile error:
| In file included from ../../../augeas-1.10.1/gnulib/lib/printf-args.h:41,
|                  from ../../../augeas-1.10.1/gnulib/lib/printf-args.c:29:
| ./wchar.h:571:6: error: #if with no expression
|  # if
|       ^
| In file included from ../../../augeas-1.10.1/gnulib/lib/mbrtowc.c:21:
| ./wchar.h:571:6: error: #if with no expression
|  # if
|       ^
| Makefile:1581: recipe for target 'printf-args.lo' failed
| make[4]: *** [printf-args.lo] Error 1

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>