lvm2: upgrade to 2.02.97 which is compatible with newer udev
* older versions are using symbols removed in newer udev
  | dmsetup.c:985: error: undefined reference to 'udev_get_dev_path'
  | collect2: error: ld returned 1 exit status
  | make[1]: *** [dmsetup] Error 1
  | make[1]: Leaving directory
  `/OE/jansa-test/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/lvm2/2.02.85-r2.0/LVM2.2.02.85/tools'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>