libldb: add pam to REQUIRED_DISTRO_FEATURES
* dependency on samba was added recently in:
  libldb: Add samba to rdeps for pyldb
  so now we need to match samba restriction to prevent:

ERROR: Nothing RPROVIDES 'samba' (but meta-oe/meta-networking/recipes-support/libldb/libldb_1.4.1.bb RDEPENDS on or otherwise requires it)
samba was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)
NOTE: Runtime target 'samba' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['samba']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libldb', 'samba']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>