psqlodbc: fix build with gcc-15
configure: make sure to call AC_CHECK_HEADER_STDBOOL before using ac_cv_sizeof_bool

It was called after this conditional, so PG_USE_STDBOOL wasn't set
even when it should be as shown in at the end of config.log:

  ac_cv_header_stdbool_h=yes
  ac_cv_sizeof_bool=1
  ac_cv_type__Bool=yes
  #define SIZEOF_BOOL 1
  #define HAVE__BOOL 1
  #define HAVE_STDBOOL_H 1

* fixes:
  https://github.com/postgresql-interfaces/psqlodbc/issues/110
  https://github.com/postgresql-interfaces/psqlodbc/issues/94

http://errors.yoctoproject.org/Errors/Details/852841/

In file included from ../psqlodbc-16.00.0000/environ.h:16,
                 from ../psqlodbc-16.00.0000/environ.c:16:
../psqlodbc-16.00.0000/psqlodbc.h:264:23: error: 'bool' cannot be defined via 'typedef'
  264 | typedef unsigned char bool;
      |                       ^~~~

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>