polkit-group-rule: package polkit rules
* broken since
  https://github.com/openembedded/meta-openembedded/pull/859
  which moved the files from ${sysconfdir} which is packaged
  in ${PN} by default into ${datadir} which isn't packaged causing:

ERROR: QA Issue: polkit-group-rule-network: Files/directories were installed but not shipped in any package:
  /usr
  /usr/share
  /usr/share/polkit-1
  /usr/share/polkit-1/rules.d
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
polkit-group-rule-network: 4 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>