python-django: add RDEPENDS
fix error:
ModuleNotFoundError: No module named 'distutils'

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Acked-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 1407d43bc4b2b8b7c2de35a4173556c08dca36a9)
Signed-off-by: Armin Kuster <akuster808@gmail.com>