bpftool: add missing build dependency
Add openssl as a dependency. Fixes compilation error:

| sign.c:16:10: fatal error: openssl/opensslv.h: No such file or directory
|    16 | #include <openssl/opensslv.h>

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>