python3-pyroute2: Add sqlite3 to RDEPENDS
python3-sqlite is required by the NDB code, irrespective of ptest:

  File "/usr/lib/python3.14/site-packages/pyroute2/__init__.py", line 31, in <module>
  File "/usr/lib/python3.14/site-packages/pyroute2/ipdb/__init__.py", line 16, in <module>
  File "/usr/lib/python3.14/site-packages/pyroute2/ndb/main.py", line 317, in <module>
  File "/usr/lib/python3.14/site-packages/pyroute2/ndb/task_manager.py", line 9, in <module>
  File "/usr/lib/python3.14/site-packages/pyroute2/ndb/schema.py", line 99, in <module>
ModuleNotFoundError: No module named 'sqlite3'

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>