paho-mqtt-c: Fix build error when enable multilib.
The error is as the following:
ERROR: paho-mqtt-c-1.3.2-r0 do_package: QA Issue: paho-mqtt-c:
Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/cmake
  /usr/lib/cmake/eclipse-paho-mqtt-c
  /usr/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig.cmake
  /usr/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfigVersion.cmake
  /usr/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig-noconfig.cmake

Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 93aa8defe3fae48c48b364136a0af8a58fd2be95)
Signed-off-by: Armin Kuster <akuster808@gmail.com>