mozjs: fix configure host contamination
When building mozjs the following error was observed

| Traceback (most recent call last):
|   File "./config.status", line 9, in <module>
|     from ConfigStatus import config_status
|   File "/build/bitbake_build/tmp/work/corei7-64-wrs-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/build/ConfigStatus.py", line 11, in <module>
|     import sys, re, os, posixpath, ntpath
|   File "/usr/lib/python2.7/ntpath.py", line 15, in <module>
|     from genericpath import _unicode
| ImportError: cannot import name _unicode
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /build//bitbake_build/tmp/work/corei7-64-wrs-linux/mozjs/17.0.0-r0/temp/do_configure/log.do_configure.1056

Note the host paths found in the error msg. Further this issue can be
explored using the host python, which will not error when attempting
the above import, and the python in the sysroot, which will fail when
we attempt the import.

By inheriting pythonnative we ensure the proper paths are set to avoid
this host contamination.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>