vboxguestdrivers: fix vboxvideo build on kernels lacking drm_fb_helper_alloc_info
Kernel 6.6.151 dropped the drm_fb_helper_alloc_info() declaration as
part of a stable backport, causing vbox_fb.c to fail with:

  vbox_fb.c:329:16: error: implicit declaration of function 'drm_fb_helper_alloc_info'

The existing RTLNX_VER_MIN(6,19,0) check can't express this since the
change landed mid-series in 6.6.y/6.12.y/6.18.y. Backport master
commit b249fbbf1be1c7c655316c46cb9aad0929ca6b8f ("vboxguestdrivers: fix
 vboxvideo build on kernels lacking drm_fb_helper_alloc_info"),
adapted for the 7.0.14 recipe.

Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>