dhex: fix error with gcc-15
* A strict error handling for function parameters in gcc-15 causes errors.
output.c:9:6: error: conflicting types for 'initcolors'; have 'void(tOutput *)' {aka 'void(struct _tOutput *)'}
    9 | void initcolors(tOutput* output)
      |      ^~~~~~~~~~
In file included from output.c:7:
output.h:10:6: note: previous declaration of 'initcolors' with type 'void(void)'
   10 | void initcolors();
      |      ^~~~~~~~~~

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>