xterm: package /usr/lib/X11 to avoid installed-vs-shipped error on ppc64
commit 'ad5d2ff6c782a3319aedc25cc641574e39328460 xterm: 308 -> 320' changed
FILES_${PN} from "/usr/lib/X11" to "${libdir}/X11". This leads to QA issue
on ppc64 which defines libdir as /usr/lib64:
ERROR: QA Issue: xterm: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/X11
  /usr/lib/X11/app-defaults
  /usr/lib/X11/app-defaults/UXTerm
  /usr/lib/X11/app-defaults/KOI8RXTerm-color
  /usr/lib/X11/app-defaults/XTerm-color
  /usr/lib/X11/app-defaults/UXTerm-color
  /usr/lib/X11/app-defaults/KOI8RXTerm
  /usr/lib/X11/app-defaults/XTerm

Restore the setting of FILES_${PN} to package the installed ASCII text files.

Signed-off-by: Ting Liu <ting.liu@nxp.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 471cd564fd72a34ac62f702fad8983f44e4b411a)
Signed-off-by: Armin Kuster <akuster808@gmail.com>