opencv: fix QA issue
Replace '/lib' with '${baselib}' to fix QA issue:

  ERROR: do_package_qa: QA Issue: non -staticdev package contains \
  static .a library: opencv-apps path \
  '.../opencv-apps/usr/share/OpenCV/3rdparty/lib64/libippicv.a' \
  [staticdev]

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit a36efdd02fe4f0702c7b412b1737ef8218089974)
Signed-off-by: Armin Kuster <akuster808@gmail.com>