vboxguestdrivers: Fix build failure due to the last update.
the utsrelease.h is not included in the STAGING_KERNEL_DIR, but in STAGING_KERNEL_BUILDDIR

So, adding a hacky symlink into the source directory fixes the issue for now.
This can be re-evaluated if poky maintainers start shipping such file into another directory or patch module*.bbclass to take account
of this additional dir into *FLAGS

https://errors.yoctoproject.org/Errors/Details/613563/

make: Entering directory 'TOPDIR/build/tmp/work/qemux86-yoe-linux/vboxguestdrivers/6.1.28-r0/vboxguestdrivers-6.1.28/utils'
i686-yoe-linux-gcc  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=TOPDIR/build/tmp/work/qemux86-yoe-linux/vboxguestdrivers/6.1.28-r0/recipe-sysroot  -I. -I../vboxsf -I../vboxsf/include -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_SUP_R0 -DVBOX -DVBOX_WITH_HGCM -DIN_MODULE -DIN_GUEST_R0 -c -o mount.vboxsf.o mount.vboxsf.c
i686-yoe-linux-gcc  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=TOPDIR/build/tmp/work/qemux86-yoe-linux/vboxguestdrivers/6.1.28-r0/recipe-sysroot  -I. -I../vboxsf -I../vboxsf/include -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_SUP_R0 -DVBOX -DVBOX_WITH_HGCM -DIN_MODULE -DIN_GUEST_R0 -c -o vbsfmount.o vbsfmount.c
In file included from ../vboxsf/include/iprt/stdarg.h:47,
                 from ../vboxsf/include/iprt/types.h:34,
                 from ../vboxsf/include/iprt/string.h:33,
                 from mount.vboxsf.c:53:
../vboxsf/include/iprt/linux/version.h:40:11: fatal error: generated/utsrelease.h: No such file or directory
   40 | # include <generated/utsrelease.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:39: recipe for target 'mount.vboxsf.o' failed

Signed-off-by: Khem Raj <raj.khem@gmail.com>