python3-webcolors: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import webcolors
 [snip]
 ModuleNotFoundError: No module named 'typing'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Acked-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>