pidgin-sipe: fix g_memdup2 changes to be backwards compatible with glib-1.67
* current version unfortunatelly it isn't backwards compatible with glib-2.0-1.66.7 currently in oe-core master and hardknott and now fails with:
| ../../../pidgin-sipe-1.25.0/src/purple/../api/sipe-common.h:56:19: error: conflicting types for 'g_memdup'
|    56 | #define g_memdup2 g_memdup
|       |                   ^~~~~~~~

that's because glibcompat.h provided by libpurple from pidgin always provides g_memdup2
so the AC_CHECK_LIB in configure.ac detects that it isn't available in glib-2.0 itself
and then tries to redefine it here.

Leave the fall-back on glibcompat.h and just replace g_memdup calls with g_memdup2.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>