gnome-system-monitor: fix build after update of gnome c++ bindings
In file included from <staging>/usr/include/c++/6.2.0/type_traits:35:0,
                 from <staging>/usr/include/sigc++-2.0/sigc++/visit_each.h:22,
                 from <staging>/usr/include/sigc++-2.0/sigc++/functors/slot.h:6,
                 from <staging>/usr/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from <staging>/usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from <staging>/usr/include/sigc++-2.0/sigc++/sigc++.h:104,
                 from <staging>/usr/include/glibmm-2.4/glibmm/thread.h:50,
                 from <staging>/usr/include/glibmm-2.4/glibmm.h:89,
                 from <staging>/usr/include/gtkmm-2.4/gtkmm.h:87,
                 from ../../gnome-system-monitor-2.28.2/src/procman.cpp:26:
<staging>/usr/include/c++/6.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit ea4abd908f4feadd17741e1f3431bb7825e69630)
Signed-off-by: Armin Kuster <akuster808@gmail.com>