xf86-video-amdgpu: add opengl to REQUIRED_DISTRO_FEATURES
Fix the below yocto compliance issue:
  ERROR: Nothing PROVIDES 'virtual/libgbm' (but /build/layers/meta-openembedded/meta-oe/recipes-graphics/xorg-driver/xf86-video-amdgpu_22.0.0.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/libc
  virtual/libomxil
  virtual/libusb0
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'xf86-video-amdgpu', 'virtual/libgbm']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>