bpftool: add native and nativesdk support
There are issues with nativesdk variant
...
ERROR: nativesdk-bpftool-1.0-r0 do_package: QA Issue:
nativesdk-bpftool: Files/directories were installed but not shipped in any package:
  /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-xesdk-linux/usr/sbin/bpftool
  /usr/share/bash-completion/completions/bpftool
...

nativesdk.bbclass sets sbindir = "${bindir}" but bpftool is installed under sbin
to fix that add sbin to FILES

for bpftool completions {prefix} is not used but it seems that bitbake expects that
installed files should be perfixed with "${SDKPATHNATIVE}${prefix_nativesdk}"
to fix that override bash_compdir

Signed-off-by: Denys Zagorui <dzagorui@cisco.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>