libtevent: add missing libaio dependency
Fixes the following compile error:
| [ 6/27] Compiling lib/replace/test/testsuite.c
| In file included from ../lib/replace/test/testsuite.c:49:0:
| ../lib/replace/system/aio.h:29:20: fatal error: libaio.h: No such file or directory
| compilation terminated.

Signed-off-by: Jonathan Liu <net147@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>