python3-docopt: add version 0.6.2
It is required by python3-pykwalify cli
...
$ pykwalify -h
x86_64-wrlinuxsdk-linux/usr/lib/python3.8/site-packages/pykwalify/cli.py", line 11, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Acked-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>