ckermit: Define return type for main
Newer compilers e.g. clang19+ will treat implicit function prototypes
as errors, therefore define main() with a valid return type

Fixes
ckwart.c:531:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  531 | main(argc,argv) int argc; char **argv; {
      | ^~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>