polkit: update 123 -> 124
- support for mozjs-115 was added, remove the patch
- update 0001-polkit.service.in-disable-MemoryDenyWriteExecute.patch
- include missing files to avoid:

  /usr/lib/pam.d
  /usr/lib/sysusers.d
  /usr/lib/pam.d/polkit-1
  /usr/lib/sysusers.d/polkit.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.

ERROR: polkit-124-r0 do_package: QA Issue: polkit: Files/directories were installed but not shipped in any package:
Signed-off-by: Khem Raj <raj.khem@gmail.com>