libopus: use armv7a, aarch64 overrides when adding ne10 dependency
* to match what ne10 recipe does now
* fixes:
  ERROR: Nothing PROVIDES 'ne10' (but meta-oe/recipes-multimedia/libopus/libopus_1.1.3.bb DEPENDS on or otherwise requires it)
  ne10 was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libopus', 'ne10']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>