python3-html2text: Add missing rdep on py3 html module
Fixes
ModuleNotFoundError: No module named 'html'

Signed-off-by: Khem Raj <raj.khem@gmail.com>