evolution-data-server: Use inherit_defer for native class
Since gnome classes are using it in core, they are now appearing after
native resulting in QA errors

ERROR: /mnt/b/yoe/master/sources/meta-openembedded/meta-gnome/recipes-gnome/evolution-data-server/evolution-data-server-native.bb: QA Issue: evolution-data-server-native: native/nativesdk class is not inherited last, this can result in unexpected behaviour. Classes inherited after native/nativesdk: pkgconfig.bbclass
siteconfig.bbclass siteinfo.bbclass autotools.bbclass [native-last]

secondly, use 'cmake' for GNOMEBASEBUILDCLASS
default is set to meson (legacy is autotools) since most of gnome recipes are using meson
these days. This recipe however uses neither autotools nor meson to
build, it uses cmake, to this effect it inherits cmake bbclass
and things worked so far, however with inherit_defer things changed because
meta/classes-recipe/gnomebase.bbclass has switched to using
inherit_defer, this unearths this issue where its not overriding
exported functions as desired. Therefore this fixes that issue

Signed-off-by: Khem Raj <raj.khem@gmail.com>