Fix build error when enable multilib.
ERROR: tracker-miners-2.3.3-r0 do_package: QA Issue: tracker-miners:
Files/directories were installed but not shipped in any package:
  /usr/lib64/systemd
  /usr/lib64/systemd/user
  /usr/lib64/systemd/user/tracker-extract.service
  /usr/lib64/systemd/user/tracker-writeback.service
  /usr/lib64/systemd/user/tracker-miner-fs.service

Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 02afb13f5dde533e97617635fdc1464fcade038c)
Signed-off-by: Armin Kuster <akuster808@gmail.com>