lvm2: replace CPPFunction with rl_completion_func_t to fix build error
lvm2 depends on readline, CPPFunction has been replaced by rl_completion_func_t
in recent readline,

Error log:
| lvm.c: In function 'lvm_shell':
| lvm.c:189:38: error: 'CPPFunction' undeclared (first use in this function)
|   rl_attempted_completion_function = (CPPFunction *) _completion;
|                                       ^

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>