libldb: Fix installed-vs-shipped and rebuild error
Fixed when multilib is disabled on intel-x86-64:
MULITLIBS = ""
$ bitbake sssd

ERROR: sssd-2.5.2-r0 do_package: QA Issue: sssd: Files/directories were installed but not shipped in any package:
/usr/lib/ldb
/usr/lib64/ldb/modules/ldb/memberof.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
sssd: 2 installed and not shipped files. [installed-vs-shipped]

And also remove bin/ got get a clean rebuild, otherwise, the rebuild result may
be incorrect.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 5f6156c0ef842bd39e9eb1f7ce02eb7c7c961d3a)
Signed-off-by: Armin Kuster <akuster808@gmail.com>