vboxguestdrivers: fix kernel v6.5 build
When building against the 6.5 kernel (and kernel headers), the following
build error is encountered:

   | vboxguestdrivers/7.0.10/vboxguestdrivers-7.0.10/vboxvideo/vbox_fb.c:194:24: error: 'drm_fb_helper_sys_fillrect' undeclared here (not in a function); did you mean 'drm_fb_helper_lastclose'?
   |   194 |         .fb_fillrect = drm_fb_helper_sys_fillrect,
   |       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
   |       |                        drm_fb_helper_lastclose
   | vboxguestdrivers/7.0.10/vboxguestdrivers-7.0.10/vboxvideo/vbox_fb.c:195:24: error: 'drm_fb_helper_sys_copyarea' undeclared here (not in a function); did you mean 'drm_fb_helper_set_par'?
   |   195 |         .fb_copyarea = drm_fb_helper_sys_copyarea,
   |       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
   |       |                        drm_fb_helper_set_par
   | vboxguestdrivers/7.0.10/vboxguestdrivers-7.0.10/vboxvideo/vbox_fb.c:196:25: error: 'drm_fb_helper_sys_imageblit' undeclared here (not in a function) |   196 |         .fb_imageblit = drm_fb_helper_sys_imageblit,
   |       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~

A patch from vbox-dev has been posted to fix the issue.

Upstream-Status: Submitted [https://www.mail-archive.com/vbox-dev@virtualbox.org/msg10129.html]

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 030f6708154054787dca7c2de95d074970115187)
Signed-off-by: Armin Kuster <akuster808@gmail.com>