gengetopt: Use std=c++14
It needs std::unary_operator which is gone in c++17, until it is forward
ported to work with c++17, pin to c++14

 ../../gengetopt-2.23/src/gm_utils.h:132:35: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
| struct pair_print_f : public std::unary_function<T, void>
|                              ~~~~~^~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>