bpftool: fix libelf.h not found error
When build host machine is not installed with elfutils-libelf-devel, it
throws compile error "libelf.h: No such file or directory". Fix missing
headers file by including path ${STAGING_INCDIR_NATIVE} via CFLAGS variable.
Use headers file from ${STAGING_INCDIR_NATIVE} instead of host machine.

Error:
| libbpf_internal.h:19:10: fatal error: libelf.h: No such file or directory

Signed-off-by: Preeti Sachan <preeti.sachan@intel.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>