thunar: fix QA issue 'installed-vs-shipped'
Since commit eb0fe21c1535 [thunar: upgrade 1.6.15 -> 1.8.0] we see a
QA Error/Warning regarding files 'installed-vs-shipped':

    ERROR: QA Issue: thunar: Files/directories were installed but not
    shipped in any package:
      /usr/lib
      /usr/lib/systemd
      /usr/lib/systemd/user
      /usr/lib/systemd/user/thunar.service

Correct the path to the systemd service file to match what we see in
other recipes which include "user" service files.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Acked-by: Andreas Müller <schnitzeltony@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>