crda: Fix usrmerge install path
Set UDEV_RULE_DIR so we follow usrmerge paths, fixing:

  ERROR: QA Issue: crda package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>