librelp: Upgrade to 1.2.18
* Correct the homepage
* Remove two backported patches
* Backport 0001-testbench-improvements.patch
  to fix the below error:
  | ../../git/src/tcp.c:3072:57: error: '%s' directive output may be truncated writing up to 1023 bytes into a region of size 1005 [-Werror=format-truncation=]
  |     snprintf(errmsg, sizeof(errmsg), "error connecting: '%s'", errStr);

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>