vlc: Add -pthread on riscv
Fixes missing atomic symols during linking e.g.

vlc-3.0.6/src/misc/picture_pool.c:201: undefined reference to `__atomic_fetch_add_2'
collect2: error: ld returned 1 exit status

Signed-off-by: Khem Raj <raj.khem@gmail.com>