libxfce4ui: check opengl DISTRO_FEATURES
Check opengl DISTRO_FEATURES to determine enable x11 in PACKAGECONFIG
or not as it make libxfce4ui depend on libepoxy when x11 enabled in
PACKAGECONFIG part.

Fixes:
  ERROR: Nothing PROVIDES 'libepoxy' (but /build/layers/meta-openembedded/meta-xfce/recipes-xfce/libxfce4ui/libxfce4ui_4.16.1.bb DEPENDS on or otherwise requires it)
  libepoxy was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'xfce4-calculator-plugin', 'libxfce4ui', 'libepoxy']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>