pidgin-sipe: allow to build with libxml2-2.11
* deprecated since libxml2-2.11 upgraded in oe-core in:
  https://git.openembedded.org/openembedded-core/commit/?id=24860598ba8557ea3a145f249938ea411f1ef1d8

* avoids:
| ../../../pidgin-sipe-1.25.0/src/core/sipe-xml.c: In function 'sipe_xml_parse':
| ../../../pidgin-sipe-1.25.0/src/core/sipe-xml.c:220:17: error: 'xmlSAXUserParseMemory' is deprecated [-Werror=deprecated-declarations]
|   220 |                 if (xmlSAXUserParseMemory(&parser, pd, string, length))
|       |                 ^~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>