mcpp: Stick to C17
* Fix build error with gcc-15 by renaming goto labels
  see more details:
  http://errors.yoctoproject.org/Errors/Details/850149/
  ../../mcpp-2.7.2/src/system.c:3436:15: error: expected identifier or '*' before 'true'

  true, false are reserved keywords in gcc-15
  Rename goto 'labels' from 'ture' to 'true_label', from 'false' 'false_label' to avoid conflicts.

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>