indent: Upgrade to 2.2.12
Add two patches to fix the build error.

Add -Wno-error=unused-value for native build
to silence below error:
| In file included from ../../indent-2.2.12/src/indent.h:60:0,
                 from ../../indent-2.2.12/src/indent.c:77:
| ../../indent-2.2.12/src/indent.c: In function 'main':
| ../../indent-2.2.12/src/libgettext.h:88:5: error: statement with no effect [-Werror=unused-value]
     ((void) (Domainname), (const char *) (Dirname))
     ^
| ../../indent-2.2.12/src/indent.c:1064:5: note: in expansion of macro 'bindtextdomain'
     bindtextdomain(PACKAGE, LOCALEDIR);

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>