lapack: fix lapack-ptest rdepends on lapack-dev
When LAPACKE is enabled, the QA check fails with the following error:
  ERROR: lapack-3.12.1-r0 do_package_qa: QA Issue: lapack-ptest rdepends on lapack-dev [dev-deps]
  ERROR: lapack-3.12.1-r0 do_package_qa: Fatal QA errors were found, failing task.
The root cause is that `lapack-ptest` accidentally installed `lapacke.pc`,
which is a development file intended to be included only in the `lapack-dev` package.
To resolve this: Remove `lapacke.pc` from the `lapack-ptest` installation

Signed-off-by: Zhang Peng <peng.zhang1.cn@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>