ntpsec: require x11 in DISTRO_FEATURES
* fixes:
  ERROR: Nothing RPROVIDES 'gnuplot' (but meta-openembedded/meta-networking/recipes-support/ntpsec/ntpsec_1.2.1.bb RDEPENDS on or otherwise requires it)
  gnuplot was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'gnuplot' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['gnuplot']
  NOTE: Runtime target 'ntpsec' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ntpsec', 'gnuplot']
  NOTE: Runtime target 'ntpsec-python' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ntpsec-python', 'gnuplot']
  ERROR: Nothing RPROVIDES 'ntpsec-dev' (but meta-openembedded/meta-networking/recipes-support/ntpsec/ntpsec_1.2.1.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'ntpsec-dev'
  NOTE: Runtime target 'ntpsec-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['ntpsec-dev']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>