freeradius: Add missing 'radiusd' static group id
This fixes build in reproducible test environment [0]:
ERROR: freeradius-3.0.26-r0 do_install: ExecutionError [...]
| chown: invalid group: ‘radiusd:radiusd’

[0]: https://autobuilder.yoctoproject.org/typhoon/#/builders/155/builds/12/steps/28/logs/stdio line 12830

Signed-off-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Khem Raj <raj.khem@gmail.com>