upm:Fix build error when enable multilib.
ERROR: upm-2.0.0+gitAUTOINC+5cf20df96c-r0 do_package: QA Issue: upm:
Files/directories were installed but not shipped in any package:
  /usr/lib/python3.8/site-packages/upm/pyupm_adc121c021.py
  /usr/lib/python3.8/site-packages/upm/pyupm_hmc5883l.py
  /usr/lib/python3.8/site-packages/upm/_pyupm_mma8x5x.so
  /usr/lib/python3.8/site-packages/upm/_pyupm_m24lr64e.so
  /usr/lib/python3.8/site-packages/upm/pyupm_tca9548a.py
  /usr/lib/python3.8/site-packages/upm/pyupm_mb704x.py
  /usr/lib/python3.8/site-packages/upm/_pyupm_ehr.so
  ......

Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit efe14bb04e58dd2028ba7c1521f08e2bd5382130)
Signed-off-by: Armin Kuster <akuster808@gmail.com>