magic-enum: Disable unused-value warning in tests
With gcc 14.1.0, there is one compilation warning found in the
unit tests which cause ptest builds to fail:

test_containers.cpp:290:89: error:
value computed is not used [-Werror=unused-value]
  290 |   magic_enum::containers::set color_set_not_const {Color::RED,
Color::GREEN, Color::BLUE};
      |

This is the same behavior as described in [1]. Thus, we can safely treat
this specific warning not as an error until the gcc bug is fixed.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=114970

Signed-off-by: Ricardo Simoes <ricardo.simoes@pt.bosch.com>
Signed-off-by: Mark Jonas <mark.jonas@de.bosch.com>
Reported-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>