python3-pkgconfig: add missing rdepends
Add missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pkgconfig
 [snip]
 ModuleNotFoundError: No module named 'shlex'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>