fetchmail: upgrade to 6.5.2 to fix build with gcc-15
* fixes:
  http://errors.yoctoproject.org/Errors/Details/852999/

../fetchmail-6.4.38/xmalloc.c:35:1: error: conflicting types for 'xrealloc'; have 'char *(char *, size_t)' {aka 'char *(char *, long unsigned int)'}
   35 | xrealloc (XMALLOCTYPE *p, size_t n)
      | ^~~~~~~~
In file included from ../fetchmail-6.4.38/xmalloc.c:9:
../fetchmail-6.4.38/xmalloc.h:28:14: note: previous declaration of 'xrealloc' with type 'char *(void *, size_t)' {aka 'char *(void *, long unsigned int)'}
   28 | XMALLOCTYPE *xrealloc(/*@null@*/ void *, size_t n);
      |              ^~~~~~~~

COPYING was updated (copyright years update and openssl note was dropped) in:
https://sourceforge.net/p/fetchmail/git/ci/62a11ca4064e5b59e57ca7a8fce08c82af259731/

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>