linuxconsole: move jscal to separate package, add to packagegroup
* migrate the changes from 'joystick' recipe in meta-ros:
  https://github.com/ros/meta-ros/commit/ee3a3f6051594bdf39322d43ec08cce0df8f172c
* add 'joystick' in PROVIDES
* provide separate joystick-jscal package
* add PACKAGECONFIG for sdl use only to build ffmvforce
* respect nonarch_base_libdir to fix QA issue with usrmerge:
  ERROR: QA Issue: joystick package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
  and
  ERROR: linuxconsole-1.7.0-r0 do_package: QA Issue: linuxconsole: Files/directories were installed but not shipped in any package:
  /lib
  /lib/udev
  /lib/udev/js-set-enum-leds
  /lib/udev/rules.d
  /lib/udev/rules.d/80-stelladaptor-joystick.rules
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  linuxconsole: 5 installed and not shipped files. [installed-vs-shipped]
  as in:
  https://github.com/ros/meta-ros/commit/9fbfe41ac55a423afd57d9e24173a5655448acd5

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>