gnome-keyring: fix 'installed but not shipped' QA issue
Building the 'gnome-keyring' recipe with "installed-vs-shipped"
included in ERROR_QA will result in:

    ERROR: gnome-keyring-3.20.0-r0 do_package: QA Issue: gnome-keyring: \
      Files/directories were installed but not shipped in any package:
      /usr/lib64/pkcs11/gnome-keyring-pkcs11.la
      /lib64/security/pam_gnome_keyring.la

>From various documents the .la files should not be packaged in either
the main recipe package or the -dev package unless required. So
inherit 'remove-libtool' to have all the .la files cleaned up as they
don't appear to be necessary.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>