aravis: fix LICENSE and enable viewer PACKAGECONFIG only with GTK3DISTROFEATURES
* fixes:
  ERROR: Nothing PROVIDES 'gtk+3' (but meta-oe/meta-multimedia/recipes-multimedia/aravis/aravis_0.8.31.bb DEPENDS on or otherwise requires it)
  gtk+3 was skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES

  and

  ERROR: QA Issue: Recipe LICENSE includes obsolete licenses LGPL-2.1 [obsolete-license]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>