swig 2.0.0: disable guile support
It's not in DEPENDS and it breaks on hosts with guile-dev installed:

configure:8391: checking whether Guile's SCM_ API works
configure:8403: ccache arm-angstrom-linux-gnueabi-gcc  -march=armv7-a -fno-tree-vectorize      -mthumb-interwork -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a8 --sysroot=/home/foo/BeagleBone/setup-scripts/build/tmp-angstrom_2010_x-eglibc/sysroots/beaglebone -o conftest -O2 -pipe -g -feliminate-unused-debug-types -Wall -W   -isystem /usr/include  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed conftest.c -ldl     -lguile -lltdl -lgmp -lcrypt -lm -lltdl >&5
cc1: warning: include location "/usr/include" is unsafe for cross-compilation
In file included from /usr/include/libguile.h:24:0,
                 from conftest.c:1:
/usr/include/gmp.h:39:21: fatal error: gmp-arm.h: No such file or directory

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>