spdlog=v1.14.1
Fixed compatibility issue between c++17 and c++11 (#3081).
Fixed creating folders under windows when full path with drive letter is given (#3079).
Added mdc sample. Note: mdc is not supported in async loggers.

* v1.14.0 introduced in:
  https://git.openembedded.org/meta-openembedded/commit/?id=a40b1fa392d20ebb29e38374d0f7ce1494bb797f
  causes:
  undefined reference to `spdlog::get(char const*)'
  in various consumers, more details in:
  https://github.com/gabime/spdlog/issues/3081

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>