mraa: Disable python2, otherwise, there is a build error when enable multilib.
ERROR: mraa-2.1.0+gitAUTOINC+e15ce6fbc7-r0 do_package: QA Issue: mraa:
Files/directories were installed but not shipped in any package:
  /usr/lib/python3.8/site-packages/_mraa.so
  /usr/lib/python3.8/site-packages/mraa.py

Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit fadaf4867074d0140e769b954b7e8afb92c4dd1a)
Signed-off-by: Armin Kuster <akuster808@gmail.com>