json-spirit: Add -latomic to LDFLAGS
This fixes following errors when compiling with clang:
| ../json_spirit/libjson_spirit.so.4.0.8: error: undefined reference to '__atomic_load_4'
| ../json_spirit/libjson_spirit.so.4.0.8: error: undefined reference to '__atomic_compare_exchange_4'
| ../json_spirit/libjson_spirit.so.4.0.8: error: undefined reference to '__atomic_fetch_sub_4'
| ../json_spirit/libjson_spirit.so.4.0.8: error: undefined reference to '__atomic_fetch_add_4'

Signed-off-by: Ming Liu <peter.x.liu@external.atlascopco.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit ac2a6d2b5d69937577effcb8bb2149651bac0176)
Signed-off-by: Armin Kuster <akuster808@gmail.com>