rtmpdump: Switch to using GNU TLS instead of openssl10
Signed-off-by: Khem Raj <raj.khem@gmail.com>
[THUD: fixes usr/include/openssl/rc4.h:74:5: error: unknown type name 'RC4_INT']
Signed-off-by: Armin Kuster <akuster808@gmail.com>