python(3)-ndg-httpsclient: use update-alternatives to avoid do_rootfs failure
Use update-alternaives to manage /usr/bin/ndg_httpclient to avoid the following
do_rootfs failure.

Error: Transaction check error:
  file /usr/bin/ndg_httpclient conflicts between attempted installs of python-ndg-httpsclient-0.5.1-r0.core2_64 and python3-ndg-httpsclient-0.5.1-r0.core2_64

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>