cunit: delete *.la files
Remove from blacklist and fix populate_sysroot issue:
ERROR: cunit-2.1-3-r0 do_populate_sysroot: QA Issue: libcunit.la failed
sanity test  (workdir) in path
.../cunit/2.1-3-r0/sysroot-destdir/usr/lib [la]
ERROR: cunit-2.1-3-r0 do_populate_sysroot: QA staging was broken by the
package built above
ERROR: cunit-2.1-3-r0 do_populate_sysroot: Function failed: do_qa_staging

Suggested-by: Koen Kooi <koen.kooi@linaro.org>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>