libconfig: fix build with gcc-15
* backport fix from:
  https://github.com/hyperrealm/libconfig/commit/690342b9cbc8b39787a1501bd890d63ca63a003c
  to fix:
  http://errors.yoctoproject.org/Errors/Details/848457/
  grammar.y:58:33: error: too many arguments to function 'libconfig_yyget_lineno'; expected 0, have 1

* need to add bison-native dependency while grammar.y is modified
  with the above patch to fix:
  http://errors.yoctoproject.org/Errors/Details/848472/
  ../aux-build/ylwrap: line 174: yacc: command not found

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>