cannelloni: Upgrade 1.1.0 -> 2.0.0 to allow CMake 4+ compatibility
- Appends -Wno-error=vla-cxx-extension to CXXFLAGS as a temporary workaround for the following Clang error:

   sctpthread.cpp:95:18: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
      95 |   uint8_t buffer[m_linkMtuSize];
         |                  ^~~~~~~~~~~~~

An upstream fix has been proposed: https://github.com/mguentner/cannelloni/pull/82

Please remove this workaround once the upstream patch is merged or fixed in some other way. Make sure it is fixed in the new version.

- Drop 0001-include-bits-stdc-.h-only-when-using-libstdc.patch because already fixed in newer version.

Changelog:

https://github.com/mguentner/cannelloni/compare/v1.1.0...v2.0.0

Fix:

| CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|   Compatibility with CMake < 3.5 has been removed from CMake.
|
|   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|   to tell CMake that the project requires at least <min> but has been updated
|   to work with policies introduced by <max> or earlier.
|
|   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
|
|
| -- Configuring incomplete, errors occurred!

Signed-off-by: Alper Ak <alperyasinak1@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>