rrdtool: add PACKAGECONFIG for dbi
* dbi was autodetected from sysroot causing undeterministic builds and failures
  in lmsensors builds:
  ld: warning: libdbi.so.1, needed by sysroots/qemux86/usr/lib/librrd.so,
  not found (try using -rpath or -rpath-link)
  sysroots/qemux86/usr/lib/librrd.so: undefined reference to `dbi_result_get_string_idx'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>