gjs: upgrade 1.72.0 -> 1.72.1
Changelog:
===========
- Various fixes ported from the development branch.

- Closed bugs and merge requests:
  * Compilation error: call to deleted function 'js_value_to_c'
  * jsapi-util-strings: Ignore locale to compute the upper case of a
    char (i.e. fix implicit properties on Turkish locale)
  * Fix memory leak when passing a "transfer none" GBytes parameter to a
    native function
  * arg-cache: Do not leak an interface info structures on Callbacks
  * test-ci: Ignore safe directory errors on CI

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 352fb4051f2584e4f28fc60348772dc99df29b7d)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>