lm_sensors: update SRC_URI
RROR: lmsensors-3.4.0-r0 do_checkuri: Fetcher failure for URL: 'http://dl.lm-sensors.org/lm-sensors/releases/lm_sensors-3.4.0.tar.bz2'. URL http://dl.lm-sensors.org/lm-sensors/releases/lm_sensors-3.4.0.tar.bz2 doesn't work
ERROR: lmsensors-3.4.0-r0 do_checkuri: Function failed: do_checkur

The project moved to google.

Signed-off-by: Armin Kuster <akuster808@gmail.com>