liboop: fix tcl PACKAGECONFIG
In case tcl PACKAGECONFIG is enabled, autoconf is trying to use tcl libs
and headers from the build system instead of using RECIPE_SYSROOT, and the
do_configure task fails:

ERROR: liboop-1.0.1-r0 do_configure: QA Issue: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. [configure-unsafe]

The system path is hardcoded in the configure script. To fix this, patch
the configure script to use pkg-config to find tcl in the correct
sysroot.

Since the previous patch was changing the same part of the script, incorporate
that also into the new patch.

Also, set the correct build-time dependency.

The patch's Upstream-Status is "Pending", because
1. The project has been without activity for almost 15 years
2. Couldn't find info on the website on how to contribute
3. The GitLab instance mentioned on the website is password protected
even for read-only access, and registration is enabled only for
specific email addresses.
4. Couldn't find any contact info on the website to reach out
to the maintainers.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>