zsh: add missing manpages PACKAGECONFIG
If zsh is built with the api-documentation enabled, the manpages.bbclass
adds the 'manpages' PACKAGECONFIG but this isn't defined:

ERROR: zsh-5.9-r0 do_configure: QA Issue: zsh: invalid PACKAGECONFIG: manpages [invalid-packageconfig]

zsh doesn't have an option to disable the manpages, so add a stub
PACKAGECONFIG to silence this error.

Signed-off-by: Ross Burton <ross.burton@arm.com>