gimp: add x11 to REQUIRED_DISTRO_FEATURES
When DISTRO_FEATURES only contains wayland, but not x11, world build
will report:
ERROR: Nothing PROVIDES 'libxmu' (but /build/layers/meta-openembedded/meta-gnome/recipes-gimp/gimp/gimp_3.0.8.bb DEPENDS on or otherwise requires it)
libxmu was skipped: using DISTRO 'poky', which is missing required DISTRO_FEATURES: 'x11'

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>