json-schema-validator: restore 0004-cmake-Use-GNUInstallDirs.patch
* it was removed in:
  https://git.openembedded.org/meta-openembedded/commit/?id=0697d52777cd530dc59bb05a506327c365bc78a2

* but the patch wasn't applied upstream yet
  and now fails in multilib builds with:
ERROR: lib32-json-schema-validator-2.2.0-r0 do_package: QA Issue: lib32-json-schema-validator: Files/directories were installed but not shipped in any package:
  /usr/lib/libnlohmann_json_schema_validator.so.2
  /usr/lib/libnlohmann_json_schema_validator.so.2.2.0
  /usr/lib/libnlohmann_json_schema_validator.so
  /usr/lib/cmake
  /usr/lib/cmake/nlohmann_json_schema_validator
  /usr/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorConfig.cmake
  /usr/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorConfigVersion.cmake
  /usr/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets.cmake
  /usr/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets-noconfig.cmake
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-json-schema-validator: 9 installed and not shipped files. [installed-vs-shipped]

https://github.com/pboettch/json-schema-validator/pull/197 was closed due to branch rename, but I don't see this change applied in:
https://github.com/pboettch/json-schema-validator/commits/main/CMakeLists.txt
so I guess the .patch is still needed.

* adjust the patch to apply on new version and restore it

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>