drbd: BLACKLIST recipe
[v2]
Wrong version sent to list. forgot to refresh

fails do to new kernel headers.

| ../drbd/9.0.8-1-r0/drbd-9.0.8-1/drbd/drbd_receiver.c:1479:7: error: 'struct bio' has no member named 'bi_bdev'; did you mean 'bi_iter'?
|   bio->bi_bdev = device->ldev->backing_bdev;
|        ^~~~~~~
|        bi_iter
| .../drbd/9.0.8-1-r0/drbd-9.0.8-1/drbd/drbd_receiver.c:1484:17: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
|   bio->bi_end_io = drbd_peer_request_endio;

Signed-off-by: Armin Kuster <akuster808@gmail.com>