sdbus-c++: Link with libatomic for rv32
Fixes
libsdbus-c++.so.1.1.0: undefined reference to `__atomic_load_8'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 5029571d689f80bfa5c3a391f088d1484c61d583)
Signed-off-by: Armin Kuster <akuster808@gmail.com>