gnome-settings-daemon: Do not generate meson.native
OE-core now uses native-file instead of environment variables
so its not needed

Fixes
ERROR: Multiple producers for Ninja target "TOPDIR/build/tmpfs/work/armv7vet2hf-neon-yoe-linux-gnueabi/gnome-settings-daemon/3.36.1-r0/meson.native". Please rename your targets.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Andreas Müller <schnitzeltony@gmail.com>
Cc: Ross Burton <ross.burton@arm.com>