krb5: Upgrade to 1.17
License-Update: Copyright year updated to 2019.

Remove one backported patch.

Fix below do_package issue:
ERROR: krb5-1.17-r0 do_package: QA Issue: krb5: Files/directories were installed but not shipped in any package:
  /usr/lib/krb5/plugins/preauth/spake.so

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>