python3-setuptools-scm: Add nativesdk to BBCLASSEXTEND
By doing so we mitigate failure when trying to bitbake recipe which
rdepends on nativesdk-python3-setuptools-scm, such as following error
when bitbaking nativesdk-python3-jsonschema:

  ERROR: Nothing RPROVIDES 'nativesdk-python3-setuptools-scm' (but virtual:nativesdk:.../meta-openembedded/meta-python/recipes-devtools/python/python3-jsonschema_3.2.0.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Niko Mauno <niko.mauno@vaisala.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit c966d3f063a9f159fd8db532b8034435e1cf3964)
Signed-off-by: Armin Kuster <akuster808@gmail.com>