python3-grpcio: revert unbundling abseil-cpp
This reverts commit 990b03b6165808cebe59886e4941bb86b05744e2.

>>> import grpc
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import grpc
  File "/usr/lib/python3.13/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/lib/python3.13/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /usr/lib/python3.13/site-packages/grpc/_cython/cygrpc.cpython-313-x86_64-linux-gnu.so: undefined symbol: _ZN4absl12lts_2024072212log_internal17kUnsignedCharNullE

Even installing whole abseil-ccp does not solve this.
ldd on this library does not include libraries containing this symbol.
Some work in linking upstram would be needed.

Signed-off-by: Peter Marko <peter.marko@siemens.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>