python3-gevent: fix build with Cython 3.0.10
Cython 3.0.10 generates code which causes compiler errors:

src/gevent/queue.c:11894:114: error: passing argument 4 of '__pyx_vtabptr_6gevent_14_gevent_cqueue_UnboundQueue->__pyx_base.put' from incompatible pointer type [-Wincompatible-pointer-types]

>From discussion upstream, removing the final decorator works around this.

Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>