python3-pillow: add 5.4.1
- Set option by modify setup.py

- Do not override do_compile to call `setup.py build_ext', it will
  missing options at do_install time which causing host contamination
  ...
  Found webp/demux.h
  Found library webpmux at /usr/lib/libwebpmux.so
  Found library webpdemux at /usr/lib/libwebpdemux.so
  /usr/include/pthread.h:682:6: error: 'regparm' is not valid on this platform
  ...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>