suitesparse: file parse error
This causes a bitbake parsing error with poky master ( https://git.yoctoproject.org/poky/commit/?h=master-next&id=33fd6f6e82cf2c9d20a0532d8cfe850280a83051 ).

```
ERROR: ExpansionError during parsing /home/ecordonnier/dev/poky/meta-openembedded/meta-oe/recipes-devtools/suitesparse/suitesparse_5.10.1.bb                                                                                             | ETA:  0:00:23
bb.data_smart.ExpansionError: Failure expanding variable CFLAGS:prepend[:=], expression was ${@" ".join(d.getVar('CC').split()[1:])}  which triggered exception AttributeError: 'NoneType' object has no attribute 'split'
The variable dependency chain for the failure is: CFLAGS:prepend[:=]

ERROR: Parsing halted due to errors, see error messages above
```

Signed-off-by: Etienne Cordonnier <ecordonnier@snap.com>