xfce4-notes-plugin: upgrade to 1.11.2
This upgrade fixes a build failure for the current 1.11.0 version.

  src/main-settings-dialog.c:175:12: error: too many arguments to function
  'notes_path_button_new'; expected 0, have 1

Note that an extra dependency is added to this new version: gtksourceview4.
It is exlicitly required in configure.ac.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>