netkit-rusers: Depend on rpcsvc-proto-native for rpcgen tool
Fixes
| rup.c:51:10: fatal error: 'rstat.h' file not found
| #include "rstat.h"
|          ^~~~~~~~~
| 1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>