gvfs: add missing dep on libsoup 2.4
| ./gvfsbackendhttp.h:28:26: fatal error: libsoup/soup.h: No such file or directory
| compilation terminated.
| make[4]: *** [gvfsd_dav-daemon-main-generic.o] Error 1

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>