ruby.bbclass: handle new installation directories
It appears that newer versions of ruby produce additional directories
which were not previously handled by the ruby bbclass, specifically
'build_info' and 'extensions'. This is currently resulting in QA
errors/warnings such as:

ERROR: QA Issue: puppet: Files/directories were installed but not shipped in any package:
  /usr/lib64/ruby/gems/2.2.0/build_info
  /usr/lib64/ruby/gems/2.2.0/extensions
Please set FILES such that these items are packaged. Alternatively if they are unneeded,
avoid installing them or delete them within do_install. [installed-vs-shipped]

Add these to our FILES in the bbclass such that they will packaged.

NOTE: several files may exist in the extensions directory such as
gem.build_complete and mkmf.log that we can most likely remove during
do_install. Since ruby installs these by default they have been left
in case their existence is used as some type of stampfile or similar.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>