syslog-ng: not deliver syslog-ng-update-virtualenv
syslog-ng-update-virtualenv causes install conflict when multilib
enabled:

Error: Transaction test error:
  file /usr/bin/syslog-ng-update-virtualenv conflicts between attempted
  installs of lib32-syslog-ng-4.0.1-r0.core2_32 and syslog-ng-4.0.1-r0.core2_64

Since python support is disabled, not deliver it.

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>