libdbus-c++: Add -pthread to linker flags
It uses symbols from libpthread e.g. pthread_mutexattr_init and pthread_mutexattr_settype
but does not link with pthreads, gold is strict about it and calls out with an error

../src/.libs/libdbus-c++-1.so: error: undefined reference to 'pthread_mutexattr_init'
../src/.libs/libdbus-c++-1.so: error: undefined reference to 'pthread_mutexattr_settype'

Therefore correct the linker cmdline

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 592e9f26cca4944adf4e534af5794680f07d098c)
Signed-off-by: Armin Kuster <akuster808@gmail.com>