gtkmm4: add x11 back to REQUIRED_DISTRO_FEATURES
x11 is moved in comit [1], but when DISTRO_FEATURES contains
opengl, but not contains x11, bitbake gtkmm4 reports:
ERROR: Nothing PROVIDES 'atkmm' (but /build/layers/meta-openembedded/meta-oe/recipes-gnome/gtk+/gtkmm4_4.20.0.bb DEPENDS on or otherwise requires it)
atkmm was skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES

[1] https://git.openembedded.org/meta-openembedded/commit/?id=2cd317e9551492a64fddf2fb535333eb7e3f7fef

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>