evince: add opengl to REQUIRED_DISTRO_FEATURES
Add opengl to REQUIRED_DISTRO_FEATURES if x11 is enabled in DISTRO_FEATURES
as it needs gnome-desktop when x11 enabled.

Fixes:
  ERROR: Nothing PROVIDES 'gnome-desktop' (but /build/layers/meta-openembedded/meta-gnome/recipes-gnome/evince/evince_42.3.bb DEPENDS on or otherwise requires it)
  gnome-desktop was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'evince', 'gnome-desktop']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>