kernel-selftest: Tests in 5.8 depend on libhugetlbfs.h
Fixes
| hmm-tests.c:24:10: fatal error: hugetlbfs.h: No such file or directory
|    24 | #include <hugetlbfs.h>
|       |          ^~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>