xterm: fix conflict between multilibs
Don't specify the program-transform-name to prevent conflict error as following:
Error: Transaction test error:
  file /usr/bin/koi8rxterm conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3
  file /usr/bin/resize.xterm conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3
  file /usr/bin/uxterm conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3
  file /usr/bin/xterm conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3
  file /usr/share/applications/uxterm.desktop conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3
  file /usr/share/applications/xterm.desktop conflicts between attempted installs of lib32-xterm-403-r0.core2_32 and xterm-403-r0.x86_64_v3

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>