python3-httpx: respect libdir in packaging
* hardcoding /usr/lib is always wrong, doesn't match with libdir e.g.
  for multilib causing:
ERROR: QA Issue: python3-httpx: Files/directories were installed but not shipped in any package:
  /usr/lib64
  /usr/lib64/python3.12
  /usr/lib64/python3.12/site-packages
  /usr/lib64/python3.12/site-packages/httpx
...
  /usr/lib64/python3.12/site-packages/httpx/__pycache__/__version__.cpython-312.pyc
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/entry_points.txt
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/WHEEL
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/METADATA
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/RECORD
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/licenses
  /usr/lib64/python3.12/site-packages/httpx-0.26.0.dist-info/licenses/LICENSE.md
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
python3-httpx: 63 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>