cfengine: remove cf-consumer.service cf-redis-server.service
* they were removed from 3.12.0 release, see:
  https://github.com/cfengine/core/commit/8001b89c098c723f0b93b311da443e2197026d88
  https://github.com/cfengine/core/commit/d8426c42c02edcfddcf785e34ac452a785b9ad3d
* fixes:
  ERROR: SYSTEMD_SERVICE_cfengine value cf-consumer.service does not exist

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>