hdf5: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/include/H5pubconf.h conflicts between attempted installs of hdf5-dev-1.14.0-r0.core2_64 and lib32-hdf5-dev-1.14.0-r0.i686

The differences between lib32-hdf5-dev and hdf5-dev are as follows:
@@ -479,10 +479,10 @@
 #define H5_SIZEOF_INT8_T 1

 /* The size of `int_fast16_t', as computed by sizeof. */
-#define H5_SIZEOF_INT_FAST16_T 4
+#define H5_SIZEOF_INT_FAST16_T 8

 /* The size of `int_fast32_t', as computed by sizeof. */
-#define H5_SIZEOF_INT_FAST32_T 4
+#define H5_SIZEOF_INT_FAST32_T 8

 /* The size of `int_fast64_t', as computed by sizeof. */
 #define H5_SIZEOF_INT_FAST64_T 8
@@ -505,16 +505,16 @@
 #if !defined(__APPLE__)

 /* The size of `size_t', as computed by sizeof. */
-#define H5_SIZEOF_SIZE_T 4
+#define H5_SIZEOF_SIZE_T 8

 /* The size of `ssize_t', as computed by sizeof. */
-#define H5_SIZEOF_SSIZE_T 4
+#define H5_SIZEOF_SSIZE_T 8

 /* The size of `long', as computed by sizeof. */
-#define H5_SIZEOF_LONG 4
+#define H5_SIZEOF_LONG 8

 /* The size of `long double', as computed by sizeof. */
-#define H5_SIZEOF_LONG_DOUBLE 12
+#define H5_SIZEOF_LONG_DOUBLE 16

 #else

@@ -538,7 +538,7 @@
   # elif defined(__aarch64__)
   #define H5_SIZEOF_LONG_DOUBLE 8
   # else
-  #define H5_SIZEOF_LONG_DOUBLE 12
+  #define H5_SIZEOF_LONG_DOUBLE 16
   # endif

 #endif
@@ -557,13 +557,13 @@
 #define H5_SIZEOF_OFF_T 8

 /* The size of `ptrdiff_t', as computed by sizeof. */
-#define H5_SIZEOF_PTRDIFF_T 4
+#define H5_SIZEOF_PTRDIFF_T 8

 /* The size of `short', as computed by sizeof. */
 #define H5_SIZEOF_SHORT 2

 /* The size of `time_t', as computed by sizeof. */
-#define H5_SIZEOF_TIME_T 4
+#define H5_SIZEOF_TIME_T 8

 /* The size of `uint16_t', as computed by sizeof. */
 #define H5_SIZEOF_UINT16_T 2
@@ -578,10 +578,10 @@
 #define H5_SIZEOF_UINT8_T 1

 /* The size of `uint_fast16_t', as computed by sizeof. */
-#define H5_SIZEOF_UINT_FAST16_T 4
+#define H5_SIZEOF_UINT_FAST16_T 8

 /* The size of `uint_fast32_t', as computed by sizeof. */
-#define H5_SIZEOF_UINT_FAST32_T 4
+#define H5_SIZEOF_UINT_FAST32_T 8

 /* The size of `uint_fast64_t', as computed by sizeof. */
 #define H5_SIZEOF_UINT_FAST64_T 8

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 9d0f892a26aa5d3f754b5cd9af77d4c442ccef12)
Signed-off-by: Armin Kuster <akuster808@gmail.com>