python3-pid: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pid
 [snip]
ModuleNotFoundError: No module named 'fcntl'
ModuleNotFoundError: No module named 'logging'
ModuleNotFoundError: No module named 'tempfile'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 580ec1e925e07484b46e76f2e7ee09d9b40c19e5)
Signed-off-by: Armin Kuster <akuster808@gmail.com>