sblim-sfcb: use -std=gnu17 for compilation
sblim-sfcb does not build under -std=gnu23 which is the default of
gcc15. Forcing -std=gnu17 fixes these build errors:
|../sblim-sfcb-1.4.9/providerMgr.c: In function 'lookupProviders':
|../sblim-sfcb-1.4.9/providerMgr.c:374:11: error: too many arguments to function 'UtilFactory->newList'; expected 0, have 2
|  374 |     lst = UtilFactory->newList(NULL, NULL);
|      |           ^~~~~~~~~~~          ~~~~
|In file included from ../sblim-sfcb-1.4.9/providerRegister.h:31,
|                 from ../sblim-sfcb-1.4.9/providerMgr.c:29:
|.../tmp/work/core2-64-poky-linux/sblim-sfcb/1.4.9/recipe-sysroot/usr/include/sfcCommon/utilft.h:202:23: note: declared here
|  202 |     UtilList       *(*newList) ();
|      |                       ^~~~~~~
|../sblim-sfcb-1.4.9/providerMgr.c: In function 'getAssocProviders':
|../sblim-sfcb-1.4.9/providerMgr.c:661:11: error: too many arguments to function 'UtilFactory->newList'; expected 0, have 2
|  661 |     lst = UtilFactory->newList(NULL, NULL);
|      |           ^~~~~~~~~~~          ~~~~
| [...]
|../sblim-sfcb-1.4.9/providerMgr.c: In function '_getConstClassChildren':
|../sblim-sfcb-1.4.9/providerMgr.c:1896:12: error: too many arguments to function 'UtilFactory->newList'; expected 0, have 2
| 1896 |       ul = UtilFactory->newList(NULL, NULL);
|      |            ^~~~~~~~~~~          ~~~~
| [...]
|../sblim-sfcb-1.4.9/providerMgr.c: In function '_getAssocClassNames':
|../sblim-sfcb-1.4.9/providerMgr.c:1945:12: error: too many arguments to function 'UtilFactory->newList'; expected 0, have 2
| 1945 |       ul = UtilFactory->newList(NULL, NULL);
|      |            ^~~~~~~~~~~          ~~~~
| [...]
|make[2]: Leaving directory '.../tmp/work/core2-64-poky-linux/sblim-sfcb/1.4.9/build'
|make[2]: *** [Makefile:1853: libsfcBrokerCore_la-providerMgr.lo] Error 1
|make[1]: Leaving directory '.../tmp/work/core2-64-poky-linux/sblim-sfcb/1.4.9/build'
|make[1]: *** [Makefile:2060: all-recursive] Error 1
|make: *** [Makefile:1112: all] Error 2
|ERROR: oe_runmake failed

Signed-off-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Khem Raj <raj.khem@gmail.com>