python3-werkzeug: add missing runtime dependencies
ModuleNotFoundError: No module named 'json'
ModuleNotFoundError: No module named 'logging'
ModuleNotFoundError: No module named 'dataclasses'
ModuleNotFoundError: No module named 'zipfile'

Signed-off-by: alperak <alperyasinak1@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>