libiodbc: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/bin/iodbc-config conflicts between attempted installs of libiodbc-3.52.15-r0.aarch64 and lib32-libiodbc-3.52.15-r0.armv7ahf_neon

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>