python3-ntplib: add missing python3-io RDEPENDS
Add the missing python3-io RDEPENDS to fix
below error:
 # python3
Python 3.8.2 (default, Apr 27 2020, 08:51:00)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import ntplib
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.8/site-packages/ntplib.py", line 32, in <module>
import socket
ModuleNotFoundError: No module named 'socket'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>