python3-icu: upgrade to 2.15.1
* 2.15 as well as 2.15.1 fail to build with gcc-15
  http://errors.yoctoproject.org/Errors/Details/852863/
  http://errors.yoctoproject.org/Errors/Details/852882/

  In file included from bases.cpp:32:
  arg.h:837:37: error: static assertion failed
    837 |   static_assert(std::is_trivial<T>::value);             \
        |                 ~~~~~~~~~~~~~~~~~~~~^~~~~

* the tarball filename is now lowercase see:
  https://pypi.org/project/pyicu/2.15/#PyICU-2.15.tar.gz
  https://pypi.org/project/pyicu/2.15.1/#pyicu-2.15.1.tar.gz

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>