networkmanager-openvpn: fix QA issue error for multilib
When enable multilib build, there is a QA Issue error:
ERROR: networkmanager-openvpn-1.2.8-r0 do_package: QA Issue: networkmanager-openvpn: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/NetworkManager
  /usr/lib/NetworkManager/VPN
  /usr/lib/NetworkManager/VPN/nm-openvpn-service.name
Please set FILES such that these items are packaged.  Alternatively if they are unneeded, avoid installing them or delete them within do_install.
networkmanager-openvpn: 4 installed and not shipped files.  [installed-vs-shipped]

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
(cherry picked from commit 028f302074e204c056990bca263433cd776efab8)
Signed-off-by: Armin Kuster <akuster808@gmail.com>