uim: Add patch to fix -fno-common link error
This is unearthed by gcc10 like below

| /mnt/b/yoe/master/build/tmp/hosttools/ld: .libs/gcroots.o:(.bss+0x0): multiple definition of `GCROOTS_jmp_buf'; .libs/mark.o:(.bss+0x0): first defined here
| /mnt/b/yoe/master/build/tmp/hosttools/ld: .libs/mach_dep.o:(.bss+0x0): multiple definition of `GCROOTS_jmp_buf'; .libs/mark.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 5c6f6797047d5d3fdf6d84c2d7fe441ed8eb89b6)
Signed-off-by: Armin Kuster <akuster808@gmail.com>