irssi: add --with-ncurses option
* otherwise do_configure tries to find ncurses.h on host and
  disables ncurses support when not found, then build fails because
  of missing -lcurses when using terminfo-core.o:
  | terminfo-core.o: In function `_set_bg':
  | /OE/irssi/0.8.15+0.8.16-rc1-r0/irssi-0.8.16-rc1/src/fe-text/terminfo-core.c:343:
    undefined reference to `tputs'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>