s3c24xx-gpio, s3c64xx-gpio, sjf2410-linux-native, usbpath, wmiconfig: use git fetcher instead of svn fetcher
* svn checkouts from http://svn.openmoko.org/ are now redirected to github:
  svn --non-interactive --trust-server-cert co --no-auth-cache --ignore-externals -r 4949 http://svn.openmoko.org/trunk/src/target/gpio@4949 gpio

Redirecting to URL 'https://github.com/openmoko/openmoko-svn':
A    gpio/branches
A    gpio/branches/oe
A    gpio/branches/oe/pre-20070305
A    gpio/branches/oe/pre-20070305/README
A    gpio/branches/oe/pre-20070305/classes
A    gpio/branches/oe/pre-20070305/classes/autotools.bbclass
A    gpio/branches/oe/pre-20070305/classes/base.bbclass
A    gpio/branches/oe/pre-20070305/classes/openmoko-base.bbclass
A    gpio/branches/oe/pre-20070305/classes/openmoko-panel-plugin.bbclass

* unfortunately this is causing the checkout to start from trunk, not the
  subdirectory specified in the URL (e.g. /trunk/src/target/gpio) and then
  S variable points to incorrect directory as discussed here:
  http://lists.openembedded.org/pipermail/openembedded-devel/2020-February/205028.html

* use git fetcher directly to remove the dependency on subversion-native

* for simplicity use the same SRCREV and PV for all of these, there wasn't any
  commit in last 8 years (not anyone can expect new commits), I don't
  expect anyone nowadays actually using these recipes which I've imported
  from meta-smartphone in 2011 - that's why I will send their removal in
  follow-up commit.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 6902dcd2edc3a08f6929e19e9a9c18493883f9d2)
[ak: fixes build issue
WARNING: s3c24xx-gpio-1.0+svnr4949-r2 do_populate_lic: Could not copy license file /home/build/builds/zeus/tmp-glibc/work/core2-64-oe-linux/s3c24xx-gpio/1.0+svnr4949-r2/gpio/gpio.c to /home/build/builds/zeus/tmp-glibc/work/core2-64-oe-linux/s3c24xx-gpio/1.0+svnr4949-r2/license-destdir/s3c24xx-gpio/gpio.c: [Errno 2] No such file or directory: '/home/build/builds/zeus/tmp-glibc/work/core2-64-oe-linux/s3c24xx-gpio/1.0+svnr4949-r2/gpio/gpio.c'
ERROR: s3c24xx-gpio-1.0+svnr4949-r2 do_populate_lic: QA Issue: s3c24xx-gpio: LIC_FILES_CHKSUM points to an invalid file: /home/build/builds/zeus/tmp-glibc/work/core2-64-oe-linux/s3c24xx-gpio/1.0+svnr4949-r2/gpio/gpio.c [license-checksum]
]
Signed-off-by: Armin Kuster <akuster808@gmail.com>