ace: fix installation paths when usrmerge is used
* INSTALL_LIB is used after INSTALL_PREFIX and in usrmerge case the /usr prefix is duplicated twice, because
  export exec_prefix="/usr"
  export base_libdir="/usr/lib"
  use baselib which is without the exec_prefix/base_prefix from root_prefis:
  #     "${@bb.utils.contains('DISTRO_FEATURES', 'usrmerge', '${exec_prefix}', '${base_prefix}', d)}"
  root_prefix="/usr"
  baselib="lib"
* fixes:
ERROR: ace-6.5.8-r0 do_package: QA Issue: ace: Files/directories were installed but not shipped in any package:
  /usr/usr/lib/libACE.so
  /usr/usr/lib/libACE_Compression.so.6.5.8
  /usr/usr/lib/libACE_ETCL_Parser.so.6.5.8
  /usr/usr/lib/libACE.so.6.5.8
  /usr/usr/lib/libACE_RLECompression.so.6.5.8
  /usr/usr/lib/libACE_Compression.so
  /usr/usr/lib/libACE_ETCL_Parser.so
  /usr/usr/lib/libACE_Monitor_Control.so.6.5.8
  /usr/usr/lib/libACE_ETCL.so
  /usr/usr/lib/libACE_RLECompression.so
  /usr/usr/lib/libACE_Monitor_Control.so
  /usr/usr/lib/libACE_ETCL.so.6.5.8
  /usr/usr/lib/pkgconfig
  /usr/usr/lib/pkgconfig/ACE.pc
  /usr/usr/lib/pkgconfig/ACE_ETCL_Parser.pc
  /usr/usr/lib/pkgconfig/ACE_ETCL.pc
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
ace: 16 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>