freerdp: upgrade 2.11.7 -> 2.11.8
Dropped 0001-Fix-const-qualifier-error.patch
* error no longer reproducible with clang

Dropped 0001-Fixed-compilation-warnings-in-ainput-channel.patch
* changes merged upstream[1]

Dropped 0001-Fixed-compilation-warnings.patch
* changes merged upstream[2]

Added 0001-Fix-compilation-error.patch to fix error:

| /yocto/bitbake-builds/poky-master/build/tmp/work/x86-64-v3-poky-linux/freerdp/2.11.8/sources/freerdp-2.11.8/winpr/libwinpr/utils/collections/Queue.c: In function 'Queue_EnsureCapacity':
| /yocto/bitbake-builds/poky-master/build/tmp/work/x86-64-v3-poky-linux/freerdp/2.11.8/sources/freerdp-2.11.8/winpr/libwinpr/utils/collections/Queue.c:169:30: error: assignment to 'void **' from incompatible pointer type 'uintptr_t *' {aka 'long unsigned int *'} [-Wincompatible-pointer-types]
|   169 |                 queue->array = newArray;
|       |

Release Notes:
https://github.com/FreeRDP/FreeRDP/releases/tag/2.11.8

Ptests passed:

START: ptest-runner
2026-03-24T19:06
BEGIN: /usr/lib/freerdp/ptest
PASS: TestClient TestClientRdpFile
...
PASS: TestWtsApi TestWtsApiWaitSystemEvent
DURATION: 180
END: /usr/lib/freerdp/ptest
2026-03-24T19:09
STOP: ptest-runner
TOTAL: 1 FAIL: 0

[1] https://github.com/FreeRDP/FreeRDP/commit/5b2b53b15c9af46b85c4ef0007e7fb59d7608289
[2] https://github.com/FreeRDP/FreeRDP/commit/d2b6771c748e54e659d5f1243a92e499c3beaa36

Signed-off-by: Ankur Tyagi <ankur.tyagi85@gmail.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>