libjxl: Turn sizeless vectors as a packageconfig option
We need to disable this on riscv64 as it results in undefined symbols
with clang especially

libjxl/0.10.2/recipe-sysroot/usr/include/hwy/ops/rvv-inl.h:591:17: error: use
of undeclared identifier '__riscv_vsetvlmax_e8mf8'
  591 | HWY_RVV_FOREACH(HWY_RVV_LANES, Lanes, setvlmax_e, _ALL)
      |                 ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>