sqlite-orm: fix build with gcc-15.0.1
* see more details:
  http://errors.yoctoproject.org/Errors/Details/850148/
    TOPDIR/tmp/work/core2-64-oe-linux/sqlite-orm/1.5/git/examples/synchronous.cpp:7:5: error: 'uint16_t' does not name a type
        7 |     uint16_t src_port;
        |     ^~~~~~~~
    TOPDIR/tmp/work/core2-64-oe-linux/sqlite-orm/1.5/git/examples/synchronous.cpp:3:1: note: 'uint16_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
        2 | #include <sqlite_orm/sqlite_orm.h>
    +++ |+#include <cstdint>
        3 | #include <string>

While this was backported from 6a96d1cec4(Explicitly included <cstdint> in examples and unit tests),
since it was a commit made in v1.9, only synchronous.cpp was modified as other files do not exist in the current version.

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>