SRC_URI master branch is deprecated and main is the new master branch
Below failure log is observed while using master branch to fetch.

ERROR: googletest-1.10.0-r0 do_fetch: Fetcher failure:
Unable to find revision 703bd9caab50b139428cea1aaff9974ebee5742e
in branch master even from upstream
ERROR: googletest-1.10.0-r0 do_fetch: Bitbake Fetcher Error:
FetchError('Unable to fetch URL from any source.',
'git://github.com/google/googletest.git;branch=master;protocol=https')

Signed-off-by: ashwin.naik <ashwin.naik@sasken.com>