meta-multimedia: fixup LAYERDEPENDS
libebml depends on dos2unix classe since 26dafa0f3542 (libebml: inherit
dos2unix), so LAYERDEPENDS needs to be updated accordingly, otherwise we are
getting a ParseError:

ERROR: ParseError at
/srv/work/oe/meta-openembedded/meta-multimedia/recipes-mkv/libebml/libebml_1.3.0.bb:13:
Could not inherit file classes/dos2unix.bbclass

It was initially found with yocto-check-layer script.

In OE/master branch, the dos2unix class was moved to oe-core, so the problem
does not exist in master, and this patch is less invasive than cherry pick the
change from master (move dos2unix from meta-oe to oe-core).

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Signed-off-by: Armin Kuster <akuster808@gmail.com>