phoronix-test-suite: exclude bash, php, python dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* otherwise the recipe cannot inherit allarch. as detected with
  openembedded-core/scripts/sstate-diff-machines.sh:

 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86copy and qemuarm ===
ERROR: phoronix-test-suite different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['bashbash_4.3.30.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'phoronix-test-suitephoronix-test-suite_6.0.1.bb.do_package', 'phoronix-test-suitephoronix-test-suite_6.0.1.bb.do_packagedata', 'phpphp_5.6.16.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'pythonpython_2.7.9.bb.do_packagedata'] to ['bashbash_4.3.30.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'phoronix-test-suitephoronix-test-suite_6.0.1.bb.do_package', 'phoronix-test-suitephoronix-test-suite_6.0.1.bb.do_packagedata', 'phpphp_5.6.16.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'pythonpython_2.7.9.bb.do_packagedata']
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-extended/bash/bash_4.3.30.bb.do_packagedata with hash 6750d401e680e6e5dac8e8585c43b386
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-extended/bash/bash_4.3.30.bb.do_packagedata with hash bc992ff361286bc2f048935132a20348
/home/jenkins/oe/world/shr-core/meta-openembedded/meta-oe/recipes-devtools/php/php_5.6.16.bb.do_packagedata with hash 17a21823eea3e0d1cce1d516f77b23ad
 changed to
/home/jenkins/oe/world/shr-core/meta-openembedded/meta-oe/recipes-devtools/php/php_5.6.16.bb.do_packagedata with hash 6058efb32e6f622aa866f982c3688f08
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-devtools/python/python_2.7.9.bb.do_packagedata with hash 4e3278467af71cb9d0219f674415a2fa
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-devtools/python/python_2.7.9.bb.do_packagedata with hash 4186010efd8bd3464948437ae114ec2a
Hash for dependent task phpphp_5.6.16.bb.do_packagedata changed from 17a21823eea3e0d1cce1d516f77b23ad to 6058efb32e6f622aa866f982c3688f08
Hash for dependent task bashbash_4.3.30.bb.do_packagedata changed from 6750d401e680e6e5dac8e8585c43b386 to bc992ff361286bc2f048935132a20348
Hash for dependent task pythonpython_2.7.9.bb.do_packagedata changed from 4e3278467af71cb9d0219f674415a2fa to 4186010efd8bd3464948437ae114ec2a

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>