pm-qa: fix build with gcc-15.0.1
* fix following error:
  http://errors.yoctoproject.org/Errors/Details/850314
    utils/uevent_reader.c: In function 'main':
    utils/uevent_reader.c:33:24: error: passing argument 2 of 'signal' from incompatible pointer type [-Wincompatible-pointer-types]
    33 |         signal(SIGINT, exit_handler);
        |                        ^~~~~~~~~~~~
        |                        |
        |                        void (*)(void)
    In file included from utils/uevent_reader.c:4:
    TOPDIR/tmp/work/core2-64-oe-linux/pm-qa/0.5.2/recipe-sysroot/usr/include/signal.h:88:57: note: expected '__sighandler_t' {aka 'void (*)(int)'} but argument is of type 'void (*)(void)'
    88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
        |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
    utils/uevent_reader.c:15:6: note: 'exit_handler' declared here
    15 | void exit_handler()
        |      ^~~~~~~~~~~~
    TOPDIR/tmp/work/core2-64-oe-linux/pm-qa/0.5.2/recipe-sysroot/usr/include/signal.h:72:16: note: '__sighandler_t' declared here
    72 | typedef void (*__sighandler_t) (int);
        |                ^~~~~~~~~~~~~~
    make: *** [<builtin>: utils/uevent_reader] Error 1

  Set PATCHTOOL to git because this recipe compiles all .c files including those in .pc/ directory which causes build errors.
  .pc/0001-fix-build-with-gcc-15-Wincompatible-pointer-types-er.patch/utils/uevent_reader.c:15:6: note: 'exit_handler' declared here
   15 | void exit_handler()

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>