grubby: Add bash to rdeps
Fixes
ERROR: QA Issue: /sbin/new-kernel-pkg contained in package grubby requires /bin/bash, but no providers found in RDEPENDS_grubby? [file-rdeps]

I wonder if new-kernel-pkg should be packaged at all, but dracut might
need to be cleaned first to not need it

Signed-off-by: Khem Raj <raj.khem@gmail.com>