linux-atm: Remove recipe
Linux commit 8f9616500c59 ("atm: remove orphaned uAPI for deleted drivers,
protocols and SVCs") deleted atm uAPI headers and ioctls in
linux/atmdev.h, legacy ATM drivers had been dropped from the kernel.

linux-atm is the userspace side of exactly those interfaces, so it no
longer builds once linux-libc-headers is 7.2:

  | ispl_l.l:15:10: fatal error: 'linux/atmsvc.h' file not found
  | ispl_y.y:15:10: fatal error: 'linux/atmsvc.h' file not found
  | src/test/isp.c:19:10: fatal error: 'linux/atmsvc.h' file not found
  | make[3]: *** [Makefile:589: ispl_y.o] Error 1

Remove the package

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>