gst-instruments: Update 0.2.3 -> 0.3.1+cb8977a
The project has moved the build system from autotools to meson. Latest
stable autotools version: 0.2.4.

Update to master: Version 0.3.1+cb8977a.

Format style with oe-stylize.py.

Add ui package to enable graphical interface.

Fix QA -dev issue:
ERROR: gst-instruments-git-r0 do_package_qa: QA Issue: -dev package
gst-instruments-dev contains non-symlink .so
'/usr/lib/libgstintercept.so'
-dev package gst-instruments-dev contains non-symlink .so
'/usr/lib/gstreamer-1.0/libgstinstruments.so' [dev-elf]

Remove dev-so from QA skip. Not required anymore.

Signed-off-by: Daniel Gomez <daniel@qtec.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>