python3-txdbus: add missing RDEPENDS
This module depends on python3-six, otherwise it errors out:

>>> from txdbus.interface import DBusInterface, Method, Signal
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    from txdbus.interface import DBusInterface, Method, Signal
  File "/usr/lib/python3.14/site-packages/txdbus/interface.py", line 8, in <module>
    import six
ModuleNotFoundError: No module named 'six'

Add the missing dependency.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>