spirv-tools: Upgrade to v2019.5
Drop upstreamed patch

backport a patch to fix

error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
|         std::move(BuildModule(env_, consumer_, original, assemble_options_));
|         ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>