evolution-data-server: update 3.56.2 -> 3.60.2
This fixes:
error: assignment to 'ICalDuration *' from 'int' makes pointer from integer without a cast [-Wint-conversion]

Evolution-Data-Server 3.60.2 2026-05-22
---------------------------------------

Bug Fixes:
	I#637 - IMAPx: Sent folder reverts to default with iCloud email and Quick Resync
	evo-I#3302 - Truncated file stored in the (mail) cache

Miscellaneous:
	e-ms-oapxbc: Simplify error handling in MS-OAPXBC OIDC extension
	e-ms-oapxbc: Fix error handling of broker response
	e-ms-oapxbc: Align D-Bus parameters with sso-mib (Felix Moessbauer)
	e-ms-oapxbc: Add support for broker versions > 2.0.1 (Felix Moessbauer)
	Do not lock SExp object in data book/cal views start
	e-book-meta-backend: Handle data: URI-s in PHOTO/LOGO
	Calendar: Use icaldurationtype_as_utc_seconds() for libical 4.x (Antonio Rojas)
	OAuth2: Use its own error domain and add camel_util_is_network_error()

Translations:
	Christian Kirbach (de)

Evolution-Data-Server 3.60.1 2026-04-10
---------------------------------------

Bug Fixes:
	I#632 - nntp: Fix GSocket ref leak in stream timeout helpers (Mikhail Gavrilov)

Miscellaneous:
	nntp: Rename nntp_get_stream_socket() to nntp_ref_stream_socket()
	ESoupSession: Correct e_soup_session_get_authentication_requires_credentials()

Evolution-Data-Server 3.60.0 2026-03-13
---------------------------------------

Bug Fixes:
	I#489 - Backends: Do not block views' start by slow connection

Miscellaneous:
	Correct ICalGLib reference in gir when building against version 4
	docs: Update libical-glib online documentation link

Translations:
	Asier Saratsua Garmendia (eu)
	Aurimas Aurimas Černius (lt)
	Balázs Úr (hu)
	Baurzhan Muftakhidinov (kk)
	Bruce Cowan (en_GB)
	Daniel Rusek (cs)

Evolution-Data-Server 3.59.3 2026-02-27
---------------------------------------

Bug Fixes:
	I#444 - Make credential prompt dialog non-modal
	I#625 - camel-sasl-ntlm: Check for integer overflow in ntlm_get_string()
	I#626 - camel-pop3-store: Compute APOP response without string allocation
	I#627 - Canonicalize path before local cache file removal
	I#628 - e-cal-recur: Check interval intersect always as date-time value
	evo-I#3257 - NNTP: Subscription dialog does not show all groups

Miscellaneous:
	e-collection-backend: Fix possible memory leak
	Use GHashTable's `replace()` instead of `insert()` on some places
	e-name-western: Crash due to double quotes in the name
	camel-network-service: Move static variable to read-only area
	credential-prompters: Add some spacing around widgets in the dialog (gtk4)
	camel-store-search: Minimize hold of the folder and folder summary locks
	camel-debug: Include object address in ref/unref backtraces
	Increase default connection timeout to 30 seconds

Translations:
	Alan Mortensen (da)
	Anders Jonsson (sv)
	Christian Kirbach (de)
	Jean-Marc TISSIERES (fr)
	Jordi Mas (ca)
	Miloš Popović (sr)
	Miloš Popović (sr@latin)
	Sabri Ünal (tr)
	twlvnn kraftwerk (bg)

Evolution-Data-Server 3.59.2 2026-01-30
---------------------------------------

Bug Fixes:
	I#617 - Calendar: Prepare to support build with libical 4.x
	M!206 - docs: Document libical-glib as dependency (Juan Luis Cano Rodríguez)

Miscellaneous:
	Correct few developer comments
	Calendar: Correct typo in error message
	Fix a compiler warning in camel-network-service.c
	e-book-utils: Correct read of a certificate from a vCard attribute
	Add ESourceConflictSearch from Evolution

Translations:
	Aurimas Aurimas Černius (lt)
	Ekaterine Papava (ka)
	Juliano de Souza Camargo (pt_BR)
	Martin (sl)
	Yuri Chornoivan (uk)

Evolution-Data-Server 3.59.1 2026-01-02
---------------------------------------

Bug Fixes:
	I#8 - Support vCard v4.0 (RFC 6350)
	I#554 - CalDAV: Provide a date limit for information sync
	I#609 - Camel: Encrypt Recipient Alias Configuration
	I#612 - Calendar: Multiple detached instances cause duplicates
	I#613 - Camel: Message info changes do not propagate sometimes
	I#614 - CamelSearchFolder: Add "not_all" "match-threads" kind
	I#616 - Crash when reading broken multipart/signed
	I#618 - Calendar: Free/busy not exported without set calendar mail
	I#620 - alarm-notify: Snooze "until X minutes before start" wrongly reminds "X min after start"
	I#621 - addressbook-export: Fails with "Invalid query" error
	M!201 - Camel: Remove camel_session_ref_service_by_url (Corentin Noël)
	M!203 - Remove several migration functions from Evolution Source Registry (Corentin Noël)
	evo-I#3157 - Broken multipart/signed shown as raw MIME data

Miscellaneous:
	org.gnome.EvolutionDataServer.Devel.json: Build also gweather-locations
	Lower default connection timeout to 15 seconds
	evolution-source-registry: Remove unused variable (reported by compiler)
	CamelGpgContext: Improve error messages
	WebDAV: Default to no download limit
	CamelStoreDB: Keep 'sqlite_sequence' table during migration
	CamelDB: Correct return value and repeated function call arguments
	CamelStoreSearch: Unlock summary and folder when save or prepare_fetch_all fails
	IMAPx: Avoid Junk/Trash folder open when saving changes
	ERemindersWidget: Workaround too large gap between action buttons
	CamelFolderSummary: Reload from DB could leak already loaded infos
	Correct developer comment of e_source_webdav_set_limit_download_days()
	addressbook: Prefer vCard "take" functions
	CamelDataCache: Rephrase "Empty cache file" error message
	Camel: Unread count for virtual Trash/Junk folder not updated properly
	CamelStoreSearch: Ignore all errors when a message cannot be opened
	CamelStore: Speed up open folders with virtual Trash or Junk folder
	EContactAddress: Add helper functions to read, write and clear the structure
	EContact: Add EContactGeo functions to convert to/from string
	EVCard: Add conversion code for GEO attribute
	EVCard: Correct PHOTO/LOGO data: URI conversion
	EContact: Add 'timezone' field
	EVCard: Add conversion code for KEY attribute
	EContactCert: Add helper functions to work with attributes
	ECertificateWidget: Add a function to check whether any certificate data is shown
	flatpak: Add gettext ACLOCAL workaround
	EBookSqlite: Correct mutex unlock in e_book_sqlite_lock()
	EVCard: Add RFC 2739 properties into the list of known vCard 3.0 properties

Translations:
	Asier Saratsua Garmendia (eu)
	Aurimas Černius (lt)
	Daniel Rusek (cs)
	Ekaterine Papava (ka)
	Emin Tufan Çetin (tr)
	Juliano de Souza Camargo (pt_BR)
	Martin (sl)
	Sabri Ünal (tr)
	twlvnn kraftwerk (bg)
	Yuri Chornoivan (uk)

Evolution-Data-Server 3.58.0 2025-09-12
---------------------------------------

Bug Fixes:
	I#607 - test-cal-component-bag: Fails to run with source tree only

Miscellaneous:
	IMAP: Disable PREVIEW fetch on FETCH error

Translations:
	Balázs Úr (hu)
	Daniel Rusek (cs)

Evolution-Data-Server 3.57.3 2025-08-29
---------------------------------------

Bug Fixes:
	I#555 - Calendar: Deleting "This and Future Occurrences" instances can duplicate events
	I#602 - IMAP: Sometimes removes message from local summary in error
	I#604 - CamelGpgContext: Provide information about encrypted content
	I#605 - Camel: MH account busy-loops when reading directory content
	M!188 - EDataServer: Use g_object_notify_by_pspec when possible (Corentin Noël)
	M!193 - EBookContacts: Use g_object_notify_by_pspec when possible (Corentin Noël)
	M!198 - alarm-notify: Add a systemd service (Adrian Vovk)
	M!198 - data: Conditionalize installation of alarm-notify (Adrian Vovk)
	M!199 - cmake: Specify GLib minimal version to gdbus-codegen (Corentin Noël)
	M!200 - data: Set desktop directory outside the condition (Hari Rana)
	M!202 - build: Conditionally install org.gnome.Evolution-alarm-notify.desktop (Georges Basile Stavracas Neto)

Miscellaneous:
	CamelDB: Do not error out on SQLITE_ABORT
	CamelVeeFolder: Fix runtime warning when rebuilding folder content
	CamelVeeSummary: Reference subfolder in the internal hash table

Translations:
	Anders Jonsson (sv)
	Artur S0 (ru)
	Asier Saratsua Garmendia (eu)
	Jordi Mas (ca)
	Juliano de Souza Camargo (pt_BR)
	Piotr Drąg (pl)

Evolution-Data-Server 3.57.2 2025-08-01
---------------------------------------

* The libcamel API dropped CamelObject, it was not needed anymore.

Bug Fixes:
	I#449 - alarm-notify: Rework snooze options
	I#591 - alarm-notify: Sometimes uses original reminder time for modified instance
	evo-I#3089 - Camel: App freezes often when performing various threaded tasks
	evo-I#3093 - EContact: Consider also FullName as FileAs

Miscellaneous:
	CamelVeeSummary: Fix dub-subfolders annotations (Corentin Noël)
	CamelFolder: Add state saving API directly (Corentin Noël)
	Camel: Remove CamelObject (Corentin Noël)
	Camel: Remove index of deprecated symbols (Corentin Noël)
	CamelStoreSearch: Make it possible to search for a hashed message ID
	CamelFolder: Fix a memory leak
	EReminderWatcher: Debug-print what changes had been received from the calendars
	ERemindersWidget: Change gap around description text view
	CamelNetworkService: Cache the GQuark locally for the private data (Corentin Noël)
	Camel: Use g_object_notify_by_pspec when possible (Corentin Noël)
	ECal: Use g_object_notify_by_pspec when possible (Corentin Noël)
	EDataServerUI: Use g_object_notify_by_pspec when possible (Corentin Noël)
	EBook: Use g_object_notify_by_pspec when possible (Corentin Noël)
	EBackend: Use g_object_notify_by_pspec when possible (Corentin Noël)
	EDataBook: Use g_object_notify_by_pspec when possible (Corentin Noël)
	EDataCal: Use g_object_notify_by_pspec when possible (Corentin Noël)
	Camel: Use GParamSpec consistently to create properties (Corentin Noël)
	CamelVeeFolder: Fix a runtime warning when rebuilding the folder
	CamelFolderSummary: Notify about flag changes on idle
	ECalClient: Improve performance of generate_instances() function

Translations:
	Martin (sl)
	Yuri Chornoivan (uk)

Evolution-Data-Server 3.57.1 2025-06-27
---------------------------------------

* The libcamel API had been changed in several ways, some deprecated
  symbols had been removed, some API functions renamed and their return
  values changed (mostly from "transfer full" to "transfer container").

Bug Fixes:
	I#592 - Handle changed server pool in WebDAV collection sources
	I#593 - CamelDataWrapper: Correct return value of size calculate functions (dagosuhn)
	I#597 - GOA EWS: Fallback to likely EWS host URL when autodicovery fails
	M!170 - docs: Update URL to libsoup docs (Simon McVittie)
	M!176 - docs: Add docs_url argument (Corentin Noël)
	evo-I#2434 - alarm-notify: Should show a visual notification to accompany notification sounds (John Lorentzson)

Miscellaneous:
	e-data-server-util: Fix a compiler warning about 'const' qualifier discard
	libecal: Add utility functions to read and convert time to given timezone
	test-cal-utils: Add a simple additional check
	libecal: Add an ECalComponentBag object
	ESourceRegistry: Reject to create an instance when D-Bus service is not available
	Misc: Correct developer documentation annotations
	CamelService: Add private construct-only "with-proxy-resolver" property
	Camel: Add CamelStoreDB and CamelStoreSearch and use them
	Camel: Rework Search folders
	CamelFilterDriver: Remove unused "global variables"
	Camel: Rename camel_folder_summary_get_array() to camel_folder_summary_dup_uids()
	Camel: Rename camel_folder_get_uids() to camel_folder_dup_uids()
	Camel: Remove camel_folder_get_summary()
	Camel: Rename camel_folder_get_uncached_uids() to camel_folder_dup_uncached_uids()
	Camel: Rename camel_folder_summary_get_changed() to camel_folder_summary_dup_changed()
	Camel: Rename camel_uid_cache_get_new_uids() to camel_uid_cache_dup_new_uids()
	Camel: Rename CAMEL_DB_FILE to CAMEL_STORE_DB_FILE
	CamelDB: Remove unneeded public defines
	CamelProvider: Remove autodetect function (Corentin Noël)
	lib-camel-test-utils: Reference CamelProvider struct members by name in initialization
	Camel: Remove deprecated symbols from CamelStoreSummary (Corentin Noël)
	Camel: Remove deprecated symbols from CamelOfflineSettings (Corentin Noël)
	CamelStoreDB: Allow empty folder names
	CamelStoreGetFolderFlags: Remove deprecated and unused flag (Corentin Noël)
	CamelFolder: Undeprecate get/set_message_flags (Corentin Noël)
	CamelFolder: Remove deprecated functions (Corentin Noël)
	CamelFolderThread: Use the oldest message as a parent of a leaf-only subthread
	CamelFolder: Add nullable annotation to camel_folder_get_folder_summary (Corentin Noël)
	CamelFolder: Use g_object_notify_by_pspec when possible (Corentin Noël)
	CamelFolderSummary: Use g_object_notify_by_pspec when possible (Corentin Noël)
	CamelMessageInfo: Use g_object_notify_by_pspec when possible (Corentin Noël)
	CamelMimePart: Use g_object_notify_by_pspec when possible (Corentin Noël)
	CamelIMAPXMessageInfo: Use g_object_notify_by_pspec when possible (Corentin Noël)
	CamelFolderThread: Fix a crash caused by the previous commit
	Camel: Remove extra camel_pstring_free() calls
	vala: Fix several warnings thrown by Camel (Corentin Noël)
	CamelFolderSummary: Remove prepare-fetch-all signal (Corentin Noël)
	alarm-notify: Skip reminders for cancelled components
	CamelURL: Add glib-object to the header (Corentin Noël)
	CamelService: Rebase on GObject (Corentin Noël)
	CamelVeeStore: Remove unused property (Corentin Noël)
	CamelIMAPXCommand: Remove leftover assignation to CamelObject (Corentin Noël)

Translations:
	Asier Saratsua Garmendia (eu)
	Álvaro Burns (pt_BR)
	Balázs Meskó (hu)
	Boyuan Yang (zh_CN)
	Ekaterine Papava (ka)
	Emin Tufan Çetin (tr)
	Jordi Mas (ca)
	Jose Riha (sk)
	Martin (sl)
	Yuri Chornoivan (uk)

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>