minicoredumper: Switch src_uri to upstream lf git
COPYING file changed since copyright is now assined to linutronix from Erricson

Fix build on arm

Fixes error like
corestripper.c:1245:4: error: format specifies type 'unsigned long' but the arg
ument has type 'long long' [-Werror,-Wformat]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>