fftw: add virtual/fftw to PROVIDES and EXCLUDE_FROM_WORLD
* now when sysroot conflicts are fatal we really don't want to build
  multiple fftw providers in the same sysroot

  ERROR: The recipe fftwl is trying to install files into a shared area
  when those files already exist. Those files and their manifest
  location are:
     /home/jenkins/oe/world/shr-core/tmp-glibc/sysroots/qemuarm/usr/include/fftw3.f
     Matched in
	manifest-qemuarm-fftw.populate_sysroot
	manifest-qemuarm-fftwf.populate_sysroot

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>