khronos-cts: add opengl to REQUIRED_DISTRO_FEATURES
* depends on virtual/libgles2, virtual/egl and in DISTROs without opengl causes:
  ERROR: Nothing PROVIDES 'virtual/libgles2' (but meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/opengl-es-cts_3.2.6.1.bb DEPENDS on or otherwise requires it)
  ERROR: Nothing PROVIDES 'virtual/egl' (but meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/opengl-es-cts_3.2.6.1.bb DEPENDS on or otherwise requires it)
  ERROR: Nothing RPROVIDES 'opengl-es-cts-dev' (but meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/opengl-es-cts_3.2.6.1.bb RDEPENDS on or otherwise requires it)
  ERROR: Nothing RPROVIDES 'opengl-es-cts' (but meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/opengl-es-cts_3.2.6.1.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>