nmap: depend on libpcre2 not libpcre
* switched to libpcre2 in:
  https://github.com/nmap/nmap/commit/828ab48764b82d0226e860c73c5dac5b11f77385

* in builds hwere libpcre2 isn't pulled by some other dependency it was failing with:
| service_scan.h:74:10: fatal error: pcre2.h: No such file or directory                                                                                                                                                                       |    74 | #include <pcre2.h>                                                                                                                                                                                                                  |       |          ^~~~~~~~~|

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>