python3-httplib2: Upgrade 0.17.3 -> 0.18.1
Upgrade to release 0.18.1:

- explicit build-backend workaround for pip build isolation bug
  "AttributeError: 'module' object has no attribute '__legacy__'"
  on pip install
  https://github.com/httplib2/httplib2/issues/169
- IMPORTANT security vulnerability CWE-93 CRLF injection
  Force %xx quote of space, CR, LF characters in uri.
  https://cwe.mitre.org/data/definitions/93.html

PKG-INFO md5 checksum changed, the license remains the same.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Acked-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>