hunspell: use git fetcher instead of github archive
* fixes:
  ERROR: QA Issue: https://github.com/hunspell/hunspell/archive/v1.7.0.tar.gz: SRC_URI uses unstable GitHub archives [src-uri-bad]
* there is developer uploaded tarball in:
  https://github.com/hunspell/hunspell/files/2573619/hunspell-1.7.0.tar.gz
  but it's already reconfigured which we don't need, so I've used git fetcher
  to stay closer to what we already use.
* the diff between:
  https://github.com/hunspell/hunspell/files/2573619/hunspell-1.7.0.tar.gz
  and
  https://github.com/hunspell/hunspell/archive/v1.7.0.tar.gz

docker-shr @ ~/hunspell $ diff -rq hunspell-1.7.0*/
Only in hunspell-1.7.0-archive/: .gitignore
Only in hunspell-1.7.0-archive/: .travis.yml
Only in hunspell-1.7.0-archive/: COPYING.MPL
Only in hunspell-1.7.0/: INSTALL
Only in hunspell-1.7.0/: Makefile.in
Only in hunspell-1.7.0-archive/: README.md
Only in hunspell-1.7.0/: aclocal.m4
Only in hunspell-1.7.0-archive/: appveyor.yml
Only in hunspell-1.7.0/: compile
Only in hunspell-1.7.0/: config.guess
Only in hunspell-1.7.0/: config.h.in
Only in hunspell-1.7.0/: config.sub
Only in hunspell-1.7.0/: configure
Only in hunspell-1.7.0/: depcomp
Only in hunspell-1.7.0/: install-sh
Only in hunspell-1.7.0/: ltmain.sh
Only in hunspell-1.7.0-archive/m4: ChangeLog
Only in hunspell-1.7.0-archive/m4: README
Only in hunspell-1.7.0/m4: libtool.m4
Only in hunspell-1.7.0/m4: ltoptions.m4
Only in hunspell-1.7.0/m4: ltsugar.m4
Only in hunspell-1.7.0/m4: ltversion.m4
Only in hunspell-1.7.0/m4: lt~obsolete.m4
Only in hunspell-1.7.0/man: Makefile.in
Only in hunspell-1.7.0/man/hu: Makefile.in
Only in hunspell-1.7.0/: missing
Only in hunspell-1.7.0-archive/: msvc
Only in hunspell-1.7.0-archive/po: .gitignore
Only in hunspell-1.7.0/po: ca.gmo
Files hunspell-1.7.0-archive/po/ca.po and hunspell-1.7.0/po/ca.po differ
Only in hunspell-1.7.0/po: de.gmo
Files hunspell-1.7.0-archive/po/de.po and hunspell-1.7.0/po/de.po differ
Only in hunspell-1.7.0/po: es.gmo
Files hunspell-1.7.0-archive/po/es.po and hunspell-1.7.0/po/es.po differ
Only in hunspell-1.7.0/po: hu.gmo
Files hunspell-1.7.0-archive/po/hu.po and hunspell-1.7.0/po/hu.po differ
Files hunspell-1.7.0-archive/po/hunspell.pot and hunspell-1.7.0/po/hunspell.pot differ
Only in hunspell-1.7.0/po: it.gmo
Files hunspell-1.7.0-archive/po/it.po and hunspell-1.7.0/po/it.po differ
Only in hunspell-1.7.0/po: pl.gmo
Files hunspell-1.7.0-archive/po/pl.po and hunspell-1.7.0/po/pl.po differ
Only in hunspell-1.7.0/po: pt_BR.gmo
Files hunspell-1.7.0-archive/po/pt_BR.po and hunspell-1.7.0/po/pt_BR.po differ
Only in hunspell-1.7.0/po: tg.gmo
Files hunspell-1.7.0-archive/po/tg.po and hunspell-1.7.0/po/tg.po differ
Only in hunspell-1.7.0/src: Makefile.in
Only in hunspell-1.7.0/src/hunspell: Makefile.in
Only in hunspell-1.7.0-archive/src/parsers: .gitignore
Only in hunspell-1.7.0/src/parsers: Makefile.in
Only in hunspell-1.7.0-archive/src/tools: .gitignore
Only in hunspell-1.7.0/src/tools: Makefile.in
Only in hunspell-1.7.0-archive/src/tools: fuzzer.cxx
Only in hunspell-1.7.0/: tap-driver.sh
Only in hunspell-1.7.0/: test-driver
Only in hunspell-1.7.0-archive/tests: .gitattributes
Only in hunspell-1.7.0-archive/tests: .gitignore
Only in hunspell-1.7.0/tests: Makefile.in
Only in hunspell-1.7.0-archive/tests: hu.wrong
Only in hunspell-1.7.0-archive/tests: nepali.wrong
Only in hunspell-1.7.0-archive/tests: ph2.good
Only in hunspell-1.7.0-archive/tests/suggestiontest: .gitignore
Only in hunspell-1.7.0/tests/suggestiontest: Makefile.in
Only in hunspell-1.7.0-archive/tests/suggestiontest: prepare2
Only in hunspell-1.7.0-archive/tests: wordpair.good

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>