mariadb: Fix rootfs creation errors
error: file /usr/share/doc/README from install of mariadb-leftovers-5.5.46-*
conflicts with file from package dmidecode-doc-2.12-*

Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>