gnome-menus: stop configure detecting host's python
This patch does not cause python bindings builded properly (native headers included)

error message was:
ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. The path was '/home/andreas/tmp/oe-core-eglibc/work/armv7a-vfp-neon-angstrom-linux-gnueabi/gnome-menus-2.30.5-r0/gnome-menus-2.30.5'
ERROR: Function failed: do_qa_configure
ERROR: Logfile of failure stored in: /home/andreas/tmp/oe-core-eglibc/work/armv7a-vfp-neon-angstrom-linux-gnueabi/gnome-menus-2.30.5-r0/temp/log.do_configure.7913
NOTE: package gnome-menus-2.30.5-r0: task do_configure: Failed

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>