webkitgtk3: fix build on riscv64
Fix the following build failure:
Source/ThirdParty/skia/modules/skcms/src/Transform_inl.h:810:71:
error: cannot tail-call: tail call production failed
  810 |         DECLARE_STAGE(name, arg, [[clang::musttail]] return (*list.fn)(list, ctx, src, dst, \
      |                                                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
  811 |                                                                        r, g, b, a, i))
      |                                                                        ~~~~~~~~~~~~~~

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>
(cherry picked from commit e2655772498b06bf3fbd56b365b347cb130bb843)
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>