sharutils: fix build with gcc-15.0.1
* gcc-15 uses gnu23 standard for c:
  https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
  bool is included as a reserved word, causing an error due to duplicate declaration.

  Also, when parameters are empty, an error occurs. Therefore, when using
  functions from the standard library, modify the defines in configure.ac
  and source code to use standard library functions.

* ../../sharutils-4.15.2/lib/system.h:51:36: error: expected ';', identifier or '(' before 'bool'
   51 | typedef enum {false = 0, true = 1} bool;
      |                                    ^~~~
  ../../sharutils-4.15.2/lib/system.h:79:7: error: conflicting types for 'fdopen'; have 'FILE *(void)'
   79 | FILE *fdopen ();
      |       ^~~~~~
  In file included from ../lib/stdio.h:43,
                 from ../../sharutils-4.15.2/libopts/autoopts/options.h:42,
                 from ../../sharutils-4.15.2/src/shar-opts.h:49:
  recipe-sysroot/usr/include/stdio.h:299:14: note: previous declaration of 'fdopen' with type 'FILE *(int,  const char *)'
  299 | extern FILE *fdopen (int __fd, const char *__modes) __THROW
      |              ^~~~~~
  ../../sharutils-4.15.2/lib/system.h:82:7: error: conflicting types for 'popen'; have 'FILE *(void)'
   82 | FILE *popen ();
      |       ^~~~~
  recipe-sysroot/usr/include/stdio.h:893:14: note: previous declaration of 'popen' with type 'FILE *(const char *, const char *)'
  893 | extern FILE *popen (const char *__command, const char *__modes)
      |              ^~~~~
  ../../sharutils-4.15.2/src/shar.c:112:12: error: conflicting types for 'localtime'; have 'struct tm *(void)'
  112 | struct tm *localtime ();
      |            ^~~~~~~~~
  In file included from ../lib/time.h:39,
                 from ../lib/sys/stat.h:44,
                 from ../../sharutils-4.15.2/lib/system.h:32:
  recipe-sysroot/usr/include/time.h:136:19: note: previous declaration of 'localtime' with type 'struct tm *(const time_t *)' {aka 'struct tm *(const long int *)'}
  136 | extern struct tm *localtime (const time_t *__timer) __THROW;
      |                   ^~~~~~~~~
  ../../sharutils-4.15.2/src/uudecode.c:85:16: error: conflicting types for 'getpwnam'; have 'struct passwd *(void)'
   85 | struct passwd *getpwnam ();
      |                ^~~~~~~~
  In file included from ../../sharutils-4.15.2/src/uudecode.c:76:
  recipe-sysroot/usr/include/pwd.h:116:23: note: previous declaration of 'getpwnam' with type 'struct passwd *(const char *)'
  116 | extern struct passwd *getpwnam (const char *__name) __nonnull ((1));
      |                       ^~~~~~~~
      |            ^~~~~~~~~

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>