networkmanager: fix parallel build failure
Add dependency libnm_client_public_dep to libnm-client-test to fix
parallel build error:

| In file included from ../NetworkManager-1.36.0/src/libnm-client-test/nm-test-utils-impl.c:10:
| ../NetworkManager-1.36.0/src/libnm-client-public/NetworkManager.h:47:10: fatal error: nm-enum-types.h: No such file or directory
|    47 | #include "nm-enum-types.h"
|       |          ^~~~~~~~~~~~~~~~~

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit dedf55890abd21a198e16fca59ab8c7e5ff2ce62)
Signed-off-by: Armin Kuster <akuster808@gmail.com>