gyp: fix for compatibility with Python 3.10
The collections abstract base classes module is finally moved to
collections.abc starting in Python 3.10.

Fixes the following problem encountered making use of gyp:

|   File "[...]/usr/lib/python3.10/site-packages/gyp/common.py", line 497, in <module>
|     class OrderedSet(collections.MutableSet):
| AttributeError: module 'collections' has no attribute 'MutableSet'

Signed-off-by: Kurt Kiefer <kurt.kiefer@arthrex.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>