procmail: Add -Wno-implicit-int to fix error of do_compile
Without the option -Wno-implicit-int , the following error will occur and the command  procmail will not be installed to target.
lmtp.c:54:8: error: type defaults to 'int' in declaration of 'ctopfd' [-Wimplicit-int]
   54 | static ctopfd;
      |        ^~~~~~
make[1]: [Makefile:239: lmtp.o] Error 1 (ignored)

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit d23de74dc8f80b8a4abb21801dcfbef611664e9a)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>