python3-pathlib2: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pathlib2
 [snip]
 ModuleNotFoundError: No module named 'ctypes'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit e65e8da5338ac71b7e5ca8b5a781978d4c319a34)
Signed-off-by: Armin Kuster <akuster808@gmail.com>