oprofile: Fix build with binutils 2.47
binutils 2.47 removed the bfd_boolean compatibility define along with the
TRUE/FALSE macros it brought in, see binutils commit 1d95b744c069 ("Remove
bfd_boolean definition from bfd"). This breaks oprofile:

  opagent.c:81:2: error: use of undeclared identifier 'bfd_boolean'
  create_bfd.c:68:18: error: 'FALSE' undeclared

Add a patch using bool/false from <stdbool.h> instead, which is what the
bfd API has been returning since binutils 2.36.

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>