collectd: fix world build issue
ERROR: Nothing PROVIDES 'libmnl' (but /home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-extended/collectd/collectd_5.4.1.bb DEPENDS on or otherwise requires it). Close matches:
  libnl
  libyaml
  libxml2
ERROR: Required build target 'collectd' has no buildable providers.
Missing or unbuildable dependency chain was: ['collectd', 'libmnl']

remove libmnl from depends list to PACKAGECONFIG libmnl is in meta-networking.

Signed-off-by: Armin Kuster <akuster808@gmail.com>