libgxim: fix world build issues
ERROR: Nothing PROVIDES 'ruby-native' (but /home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-extended/libgxim/libgxim_0.5.0.bb DEPENDS on or otherwise requires it). Close matches:
  db-native
  bc-native
  byacc-native
ERROR: Required build target 'libgxim' has no buildable providers.
Missing or unbuildable dependency chain was: ['libgxim', 'ruby-native']

move libgxim from meta-oe to meta-ruby, it really belongs in meta-gir but it is un-maintained.

Signed-off-by: Armin Kuster <akuster808@gmail.com>