libosinfo: update 1.11.0 -> 1.12.0
- remove backported patch
- add a patch to fix:
| ../git/osinfo/osinfo_loader.c:357:5: error: 'content' is deprecated [-Werror=deprecated-declarations]
|   357 |     ret = g_strdup((char *)buf->content);
|       |     ^~~
| In file included from /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libosinfo/1.12.0/recipe-sysroot/usr/include/libxml2/libxml/parser.h:16,
|                  from ../git/osinfo/osinfo_loader.c:29:
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libosinfo/1.12.0/recipe-sysroot/usr/include/libxml2/libxml/tree.h:103:14: note: declared here
|   103 |     xmlChar *content XML_DEPRECATED_MEMBER;
|       |              ^~~~~~~
| ../git/osinfo/osinfo_loader.c: At top level:
| ../git/osinfo/osinfo_loader.c:1905:42: error: expected ';', ',' or ')' before 'ATTRIBUTE_UNUSED'
|  1905 | catchXMLError(void *ctx, const char *msg ATTRIBUTE_UNUSED, ...)
|       |                                          ^~~~~~~~~~~~~~~~
| ../git/osinfo/osinfo_loader.c: In function 'osinfo_loader_process_xml':
| ../git/osinfo/osinfo_loader.c:1948:25: error: 'catchXMLError' undeclared (first use in this function)
|  1948 |     pctxt->sax->error = catchXMLError;
|       |                         ^~~~~~~~~~~~~
| ../git/osinfo/osinfo_loader.c:1948:25: note: each undeclared identifier is reported only once for each function it appears in
| cc1: all warnings being treated as errors

1.12.0 - Oct 23, 2023
=====================

- Some memory leak fixes #156
- Adapt to change in libxml2 #155
- Several CI improvements
- Several translations improvements

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Khem Raj <raj.khem@gmail.com>