ldns: Disable GOST support
ldns implements GOST exclusively through the OpenSSL ENGINE API, which was
removed in OpenSSL 4.0

Causes

  ./keys.c:664:5: error: use of undeclared identifier 'ldns_key_new_frm_fp_gost_l'
    664 |                                 ldns_key_new_frm_fp_gost_l(fp, line_nr));
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~

USE_GOST gets defined because configure probes for a
working GOST engine using AC_RUN_IFELSE, which cannot run when cross
compiling and therefore falls back to "maybe", which is treated as success.

Pass --disable-gost since the feature cannot work at all without ENGINE
support.

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>