packagegroup-meta-initramfs: remove klibc utilities and kexec-tools-klibc
klibc utils have no update-alternatives because these live ideally alone
in the initramfs. mwta-initramfs image is not minimal having busybox, linux-
utils,coreutils so to resolve the conflict we remove the shared klibc utils.

The image is mostly for build-tests and contains dracut, which does not have
runtime dependencies on kexec-tools, so we can safely remove the klibc
static version of kexec and vmcore-dmesg (not availaible on some archs).
Doing this we can safely remove EXCLUDE_FROM_WORLD

Fix:
ERROR: meta-initramfs-image-1.0-r0 do_rootfs:
Postinstall scriptlets of ['busybox', 'util-linux-umount',
'util-linux-dmesg','coreutils', 'util-linux-mount', 'cpio',
'util-linux-kill', 'util-linux-losetup'] have failed.

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>