minizip: Make rconflicts with minizip-ng
Fixes:
  Error: Transaction test error:
  file /usr/bin/minizip conflicts between attempted installs of minizip-1.3.1-r0.riscv64 and minizip-ng-4.0.8-r0.riscv64
  file /usr/lib/libminizip.so.1 conflicts between attempted installs of minizip-1.3.1-r0.riscv64 and minizip-ng-4.0.8-r0.riscv64

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>