daq: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/bin/daq-modules-config conflicts between attempted installs of lib32-daq-2.0.7-r0.armv7ahf_neon and daq-2.0.7-r0.cortexa57

The differences of daq-modules-config are as follows:
@@ -7,7 +7,7 @@

 prefix=/usr
 exec_prefix=/usr
-LIBDIR=/usr/lib64
+LIBDIR=/usr/lib
 STATIC_LIBS=" -lsfbpf -lpcap -lsfbpf -lnfnetlink -lnetfilter_queue -lsfbpf -lpcap  -ldnet"

 static=0

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>