gtkwave: add the libtirpc dependence and config
Since the oe-core commit "libtirpc: create the symbol link for rpc
header files" create the symbol link of header files, so during
checking it will find the related header files, then it will use
the old PRC_LDADD value "-lrpc" other than "-ltirpc".
So we add the option "--with-tirpc" to the configure command and
add the dependence.

Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 26fdb6f16869744b9e9ce717dffd2f89170d51e9)

Fixes build issue:

TOPDIR/tmp/work/core2-64-poky-linux/gtkwave/3.3.98-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/9.2.0/ld: vzt_write.o: in function `vzt_wr_emit_value_double':
/usr/src/debug/gtkwave/3.3.98-r0/build/src/helpers/../../../gtkwave-3.3.98/src/helpers/vzt_write.c:1637: undefined reference to `xdrmem_create'

Signed-off-by: Armin Kuster <akuster808@gmail.com>