grpc: Define libdir and cmakedir in terms of multilib
This helps in avoiding packaging errors seen with distros enabling
multilib

Fixes

ERROR: grpc-1.24.3-r0 do_package: QA Issue: grpc: Files/directories were installed but not shipped in any package:
  /usr/lib/libgrpc++.so.1.24.3
  ...
  /usr/lib/cmake
  /usr/lib/cmake/grpc
  /usr/lib/cmake/grpc/gRPCConfigVersion.cmake
  /usr/lib/cmake/grpc/gRPCConfig.cmake
  /usr/lib/cmake/grpc/gRPCTargets-noconfig.cmake
  /usr/lib/cmake/grpc/gRPCTargets.cmake
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or de
lete them within do_install.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit e18d8c957034908f27350e6ffcae2a3d05a4387b)
Signed-off-by: Armin Kuster <akuster808@gmail.com>