python-phoneutils: drop due to lack of libphone-utils
ERROR: Nothing PROVIDES 'libphone-utils' (but meta-openembedded/meta-oe/recipes-devtools/python/python-phoneutils_git.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'python-phoneutils' has no buildable providers.

Signed-off-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>