tepl: Add missing dep on python3-pygments-native
Fixes
  File "TOPDIR/build/tmp/work/cortexa15t2hf-neon-yoe-linux-gnueabi/tepl/6.2.0-r0/recipe-sysroot-native/usr/share/gtk-doc/python/gtkdoc/highlight.py", line 27, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'

Signed-off-by: Khem Raj <raj.khem@gmail.com>