unixodbc: Fix install conflict when enable multilib.
 Error: Transaction test error:
   file /usr/include/unixODBC/config.h conflicts between attempted installs of unixodbc-dev-2.3.11-r0.aarch64 and lib32-unixodbc-dev-2.3.11-r0.armv7ahf_neon
   file /usr/include/unixODBC/unixodbc_conf.h conflicts between attempted installs of unixodbc-dev-2.3.11-r0.aarch64 and lib32-unixodbc-dev-2.3.11-r0.armv7ahf_neon
   file /usr/include/unixodbc.h conflicts between attempted installs of unixodbc-dev-2.3.11-r0.aarch64 and lib32-unixodbc-dev-2.3.11-r0.armv7ahf_neon

 The differences of config.h are as follows:
 @@ -14,7 +14,7 @@
  /* #undef C_ALLOCA */

  /* Lib directory */
 -#define DEFLIB_PATH "/usr/lib64"
 +#define DEFLIB_PATH "/usr/lib"

  /* Using perdriver iconv */
  /* #undef ENABLE_DRIVER_ICONV */
 @@ -275,7 +275,7 @@
  #define INCLUDE_PREFIX "/usr/include"

  /* Lib directory */
 -#define LIB_PREFIX "/usr/lib64"
 +#define LIB_PREFIX "/usr/lib"

  /* Define to the sub-directory where libtool stores uninstalled libraries. */
  #define LT_OBJDIR ".libs/"
 @@ -311,7 +311,7 @@
  #define PACKAGE_VERSION "2.3.11"

  /* Platform is 64 bit */
 -#define PLATFORM64 /**/
 +/* #undef PLATFORM64 */

  /* Install prefix */
  #define PREFIX "/usr"
 @@ -323,10 +323,10 @@
  #define SHLIBEXT ".so"

  /* The size of `long', as computed by sizeof. */
 -#define SIZEOF_LONG 8
 +#define SIZEOF_LONG 4

  /* The size of `long int', as computed by sizeof. */
 -#define SIZEOF_LONG_INT 8
 +#define SIZEOF_LONG_INT 4

  /* If using the C implementation of alloca, define if you know the
     direction of stack growth for your system; otherwise it will be
 @@ -351,7 +351,7 @@
  #define SYSTEM_FILE_PATH "/etc"

  /* Lib path */
 -#define SYSTEM_LIB_PATH "/usr/lib64"
 +#define SYSTEM_LIB_PATH "/usr/lib"

  /* Define to 1 if you can safely include both <sys/time.h> and <time.h>. This
     macro is obsolete. */
 @@ -383,7 +383,7 @@
  /* #undef _ALL_SOURCE */

  /* Number of bits in a file offset, on hosts where this is settable. */
 -/* #undef _FILE_OFFSET_BITS */
 +#define _FILE_OFFSET_BITS 64

  /* Define to 1 to make fseeko visible on some hosts (e.g. glibc 2.2). */
  /* #undef _LARGEFILE_SOURCE */

 The differences of unixodbc_conf.h are as follows:
 @@ -19,7 +19,7 @@
  /* #undef C_ALLOCA */

  /* Lib directory */
 -#define DEFLIB_PATH "/usr/lib64"
 +#define DEFLIB_PATH "/usr/lib"

  /* Using perdriver iconv */
  /* #undef ENABLE_DRIVER_ICONV */
 @@ -342,7 +342,7 @@
  #define INCLUDE_PREFIX "/usr/include"

  /* Lib directory */
 -#define LIB_PREFIX "/usr/lib64"
 +#define LIB_PREFIX "/usr/lib"

  /* Define if the OS needs help to load dependent libraries for dlopen(). */
  /* #undef LTDL_DLOPEN_DEPLIBS */
 @@ -396,7 +396,7 @@
  /* Define to the version of this package. */

  /* Platform is 64 bit */
 -#define PLATFORM64 /**/
 +/* #undef PLATFORM64 */

  /* Install prefix */
  #define PREFIX "/usr"
 @@ -408,7 +408,7 @@
  #define SHLIBEXT ".so"

  /* The size of `long', as computed by sizeof. */
 -#define SIZEOF_LONG 8
 +#define SIZEOF_LONG 4

  /* If using the C implementation of alloca, define if you know the
     direction of stack growth for your system; otherwise it will be
 @@ -431,7 +431,7 @@
  #define SYSTEM_FILE_PATH "/etc"

  /* Lib path */
 -#define SYSTEM_LIB_PATH "/usr/lib64"
 +#define SYSTEM_LIB_PATH "/usr/lib"

  /* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
  #define TIME_WITH_SYS_TIME 1

 The differences of unixodbc.h are as follows:
 @@ -14,4 +14,4 @@
  #define HAVE_UNISTD_H 1

  /* Define to the value of sizeof(long) */
 -#define SIZEOF_LONG_INT 8
 +#define SIZEOF_LONG_INT 4

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>