libdnet: Update SRC_URI to fix checksum errors
ERROR: libdnet-1.12-r0 do_fetch: Fetcher failure for URL: 'https://github.com/dugsong/libdnet/archive/libdnet-1.12.tar.gz'. Checksum mismatch!
File: '/home/akuster/oss/downloads/libdnet-1.12.tar.gz' has md5 checksum d2f1b72eac2a1070959667e9e61dcf20 when 9253ef6de1b5e28e9c9a62b882e44cc9 was expected
File: '/home/akuster/oss/downloads/libdnet-1.12.tar.gz' has sha256 checksum b6360659c93fa2e3cde9e0a1fc9c07bc4111f3448c5de856e095eb98315dd424 when 83b33039787cf99990e977cef7f18a5d5e7aaffc4505548a83d31bd3515eb026 was expected

use Gentoo url instead of github

Signed-off-by: Armin Kuster <akuster808@gmail.com>