python3-ptyprocess: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import ptyprocess
 [snip]
 ModuleNotFoundError: No module named 'fcntl'
 ModuleNotFoundError: No module named 'pty'
 ModuleNotFoundError: No module named 'resource'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>