rdist: fix parallel build
It fails to compile rdist occasionally when system load of build server
is high:

| In file included from common.c:57:
| ../include/defs.h:49:10: fatal error: y.tab.h: No such file or directory
|    49 | #include "y.tab.h"
|       |          ^~~~~~~~~
| compilation terminated.

Make $(COMMONOBJS) which include common.o to depends on related header files
and y.tab.h to fix the parallel build failure.

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>