networkmanager: fix QA issue error for multilib
When enable multilib build, there is a QA Issue error:
ERROR: networkmanager-1.10.6-r0 do_package: QA Issue: networkmanager: Files/directories were installed but not shipped in any package:
  /usr/lib/NetworkManager
  /usr/lib/NetworkManager/VPN
  /usr/lib/NetworkManager/conf.d
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
networkmanager: 3 installed and not shipped files.  [installed-vs-shipped]

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
(cherry picked from commit 9a654a35b7deb9ad530003bd8b2be7c65e6b38c8)
Signed-off-by: Armin Kuster <akuster808@gmail.com>