python3-aiohttp: add buildpath HOME check exception due to upstream pkg
The upstream tarball fetched from pypi contains `.hash` files like these:

  $ cat aiohttp/.hash/hdrs.py.hash
  a46ad6c3a2faf8d26a2c6afc1a2210ce379a23f2799fce7b26a01f6ce5a40642  /home/runner/work/aiohttp/aiohttp/aiohttp/hdrs.py

These file trigger the relatively new HOME buildpath check _if_ the recipe
happens to be built by someone with HOME set to /home/runner
(for example someone building in a GitHub workflow):

  ERROR: python3-aiohttp-3.14.1-r0 do_package_qa: QA Issue:
  File /usr/lib/python3.14/site-packages/aiohttp/.hash/hdrs.py.hash
  in package python3-aiohttp contains a reference to the build host HOME directory.
  If upstream hardcodes a directory path that matches your home,
  you can set OEQA_BUILDPATHS_SKIP = "/home/runner" in the recipe. [buildpaths]

Follow the suggested fix of setting `OEQA_BUILDPATHS_SKIP`.
See also openembedded-core commit ee29a9132a ("oeqa: allow exceptions in
buildpath HOME checks") for an example of `OEQA_BUILDPATHS_SKIP` used.

Signed-off-by: Leonard Göhrs <l.goehrs@pengutronix.de>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>