sysbench: avoid -L/usr/lib32 and configure-unsafe QA issue
* when libdir isn't /usr/lib (e.g. /usr/lib32 with multilib), then
  m4/lib-prefix.m4 can add additional_libdir=\"$libdir\":

    dnl Potentially add $additional_libdir to $LDFLAGS.
    dnl But don't add it
    dnl   1. if it's the standard /usr/lib,
    dnl   2. if it's already present in $LDFLAGS,
    dnl   3. if it's /usr/local/lib and we are using GCC on Linux,
    dnl   4. if it doesn't exist as a directory.
    if test "X$additional_libdir" != "X/usr/$acl_libdirstem"; then

  this doesn't happen in regular builds because of condion 1. above

* fixes:
  ERROR: QA Issue: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
  Rerun configure task after fixing this. [configure-unsafe]

* drop libaio from DEPENDS as it's added by PACKAGECONFIG when enabled

* I've also tried to drop brokensep as it was added in:
  https://git.openembedded.org/meta-openembedded/commit/?id=bb31da87599853b2e5d4d4adc641a93edb22cd16
  https://github.com/openembedded/meta-openembedded/pull/632/commits/d2265dbacdb9e7bd7d6e4a9f1a2b3cc1633fb328

  without any explation why brokensep was needed for 1.0.20 (while it wasn't used in 0.4.12 version)

  and it looks like luajit detection fails without broken sep and build with internal luajit then fails with:
  ./lua/internal/sysbench.lua.h:1:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '/' token
    1 | unsigned char __/__/__/__/git/src/lua/internal/sysbench_lua[] =
      |                 ^

  but I'll leave this to someone actually using sysbench

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>