mdio-tools: Add virtual/kernel dependency to avoid stale SPDX reference
OpenBMC enables SPDX SBOM generation by default. For Meta's Bletchley
platform we found that mdio-tools and its relationships with both
mdio-netlink and the mdio-netlink kernel module break SPDX processing
while generating the rootfs after a kernel bump. For example, the
following output was generated by `bitbake obmc-phosphor-image`:

    ERROR: obmc-phosphor-image-1.0-r0 do_rootfs: Cannot find any SPDX file for document http://spdx.org/spdxdoc/kernel-module-mdio-netlink-6.5.4-da279e9-00089-gda279e98c07f-89187488-3164-50cb-94c5-8b76a30ea093

The error occurred after the following patch was applied (again, in the
context of OpenBMC):

    diff --git a/meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb b/meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb
    index e6f98297c540..b852e993f0f6 100644
    --- a/meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb
    +++ b/meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb
    @@ -1,6 +1,6 @@
     KBRANCH ?= "dev-6.5"
    -LINUX_VERSION ?= "6.5.4"
    +LINUX_VERSION ?= "6.5.9"

    -SRCREV="da279e98c07f9c948c60a434ab0043a55c26ea1d"
    +SRCREV="fc8d4fdba5bd2b9b1cea2aa8a731531943c45aa7"

     require linux-aspeed.inc

With the lack of a dependency the mdio-tools package is not rebuilt
subsequent to the kernel bump and the package information remains stale,
leading to an incorrect SPDX path being generated.

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>
Signed-off-by: Khem Raj <raj.khem@gmail.com>