yaffs2-utils: Upgrade to 20221209
* The 20221209 is the commit date of SRCREV since this recipe has no version.
* Add 0001-yaffs_guts.h-define-YTIME_T-if-not-already-defined.patch to fix
  build error:
  yaffs_guts.h:501:9: error: unknown type name 'YTIME_T'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>