python3-can: Add typing-extensions dependency
The python-can 4.0.0 release introduced a dependency on the
typing_extensions module:

    $ python3
    Python 3.8.10 (default, Mar 15 2022, 12:22:08)
    [GCC 9.4.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import can
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "python-can/can/__init__.py", line 17, in <module>
        from .listener import Listener, BufferedReader, RedirectReader, AsyncBufferedReader
      File "python-can/can/listener.py", line 12, in <module>
        from can.message import Message
      File "python-can/can/message.py", line 11, in <module>
        from . import typechecking
      File "python-can/can/typechecking.py", line 9, in <module>
        import typing_extensions
    ModuleNotFoundError: No module named 'typing_extensions'

Signed-off-by: Ben Powell <ben_powell@trimble.com>
Signed-off-by: Theodore A. Roth <theodore_roth@trimble.com>
Signed-off-by: Theodore A. Roth <troth@openavr.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>