libsdl3: update 3.2.10 -> 3.2.12
- do not disable xrandr to avoid:

| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:506:13: error: unknown type name 'XRRScreenResources'
|   506 |             XRRScreenResources *screen = X11_XRRGetScreenResourcesCurrent(display, DefaultRootWindow(display));
|       |             ^~~~~~~~~~~~~~~~~~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:506:42: error: implicit declaration of function 'X11_XRRGetScreenResourcesCurrent' [-Wimplicit-function-declaration]
|   506 |             XRRScreenResources *screen = X11_XRRGetScreenResourcesCurrent(display, DefaultRootWindow(display));
|       |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:506:42: error: initialization of 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:507:13: error: unknown type name 'XRRCrtcInfo'
|   507 |             XRRCrtcInfo *crtc_info = X11_XRRGetCrtcInfo(display, screen, screen->crtcs[0]);
|       |             ^~~~~~~~~~~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:507:38: error: implicit declaration of function 'X11_XRRGetCrtcInfo' [-Wimplicit-function-declaration]
|   507 |             XRRCrtcInfo *crtc_info = X11_XRRGetCrtcInfo(display, screen, screen->crtcs[0]);
|       |                                      ^~~~~~~~~~~~~~~~~~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:507:80: error: request for member 'crtcs' in something not a structure or union
|   507 |             XRRCrtcInfo *crtc_info = X11_XRRGetCrtcInfo(display, screen, screen->crtcs[0]);
|       |                                                                                ^~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:508:27: error: request for member 'width' in something not a structure or union
|   508 |             x = (crtc_info->width - data->dialog_width) / 2;
|       |                           ^~
| /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libsdl3/3.2.12/SDL3-3.2.12/src/video/x11/SDL_x11messagebox.c:509:27: error: request for member 'height' in something not a structure or union
|   509 |             y = (crtc_info->height - data->dialog_height) / 3;
|       |

This is a stable bugfix release, with the following changes:

    Fixed crash if SDL_BlitSurfaceScaled() is used with a surface that has no pixels
    Removed timeout in SDL_RunOnMainThread()
    Allow rendering a zero sized source rectangle in the SDL render API
    Fixed texture colorspace when creating a texture from a surface with the SDL render API
    Renamed SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_UINT8 to SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER
    Allow a NULL shader entry point for SDL_GPUShaderCreateInfo, defaulting to the one used by SDL_shadercross
    Fixed failing to create a GPU device if the D3D12 debug layers aren't available on Windows
    Added support for the share button on the GameSir-K1 FLUX controller
    Added support for the PowerA Battle Dragon Advanced Wireless Controller
    Added support for the HORI Taiko No Tatsujin Drum Controller
    Fixed the Keychron K1 Pro System Control keyboard being detected as a joystick
    Fixed right mouse button emulation when using a Wacom tablet in Windows Ink mode
    Fixed missing simulated mouse events using a Wacom tablet when Windows Ink mode is disabled
    Fixed process I/O redirection to NUL on Windows
    Key events are now sent for dead keys on X11
    Improved handling of window management edge conditions on X11
    Fixed message box location on multi-monitor configurations on X11
    Fixed XInput2 mouse tracking outside the window on X11
    Fixed window focus after showing a file dialog on macOS
    Ignore mouse clicks and motion on tooltip windows on macOS
    Fixed message boxes shown on a background thread on iOS
    Fixed Android audio crackling introduced in 3.2.10
    Fixed handling of SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY
    Fixed A/B/X/Y buttons on Nintendo 3DS
    Fixed building for Xbox One

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Khem Raj <raj.khem@gmail.com>