libblockdev: fix QA error in case of multilib
Fix the following QA error.

ERROR: QA Issue: libblockdev: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python3.11
  /usr/lib/python3.11/site-packages
  /usr/lib/python3.11/site-packages/gi
  /usr/lib/python3.11/site-packages/gi/overrides
  /usr/lib/python3.11/site-packages/gi/overrides/BlockDev.py

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit a76f0b1f7c9fc7ecb4ebaaf9862fff3624fdef53)
Signed-off-by: Armin Kuster <akuster808@gmail.com>