nbd: Do not inherit systemd
It does not provide/enable systemd script generation which results in

ERROR: nbd-3.26.1-r0 do_package: nbd does not appear in package list, please add it

Signes-off-by: Khem Raj <raj.khem@gmail.com>