libxfce4ui: update REQUIRED_DISTRO_FEATURES
Refer [1], when DISTRO_FEATURES contains opengl, but not x11, world
build will report:
ERROR: Nothing PROVIDES 'libice' (but /build/layers/meta-openembedded/meta-xfce/recipes-xfce/libxfce4ui/libxfce4ui_4.20.2.bb DEPENDS on or otherwise requires it)
libice was skipped: using DISTRO 'poky', which is missing required DISTRO_FEATURES: 'x11'

[1] https://git.openembedded.org/meta-openembedded/commit/?id=bd206048b6fabe22a67058aaf250a28d00d92135

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>