gtk-vnc: add x11 to REQUIRED_DISTRO_FEATURES
Fix world build failure:
ERROR: Nothing PROVIDES 'libx11' (but /build/layers/meta-openembedded/meta-gnome/recipes-connectivity/gtk-vnc/gtk-vnc_1.5.0.bb DEPENDS on or otherwise requires it)
libx11 was skipped: using DISTRO 'poky', which is missing required DISTRO_FEATURES: 'x11'

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>