lv-lib-png: add wayland to REQUIRED_DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'lvgl' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb DEPENDS on or otherwise requires it)
lvgl was skipped: missing required distro feature 'wayland' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'lv-lib-png-dev' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lv-lib-png-dev'
NOTE: Runtime target 'lv-lib-png-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lv-lib-png-dev']
ERROR: Nothing RPROVIDES 'lv-lib-png' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lv-lib-png'
NOTE: Runtime target 'lv-lib-png' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lv-lib-png']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>