abseil-cpp: fix mingw build
Add patch to fix mingw build of abseil-cpp

  undefined reference to `absl::lts_20230802::synchronization_internal::Win32Waiter::Poke()'
  undefined reference to `absl::lts_20230802::synchronization_internal::Win32Waiter::Win32Waiter()'
  undefined reference to `absl::lts_20230802::synchronization_internal::Win32Waiter::Post()'
  undefined reference to `absl::lts_20230802::synchronization_internal::Win32Waiter::Poke()'

and include bindir to recipe sysroot to fix protobuf build.

|   The imported target "absl::log_severity" references the file
|
|      "../nativesdk-protobuf/4.23.4/recipe-sysroot/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-w64-mingw32/usr/bin/libabsl_log_severity.dll"
|
|   but this file does not exist.

Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit ca4c5ab653b9d5187385050552386f95ec868944)