layer.conf: Add ttf-takao to SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS on fontconfig
* this issue was introduced in:
  https://git.openembedded.org/meta-openembedded/commit/?id=f58bd1789ad840b04fa36212d67cebbe14ed21e5

* fixes issue detected with sstate-diff-machine.sh:

 === Comparing signatures for task do_package_write_ipk.sigdata between tissot and raspberrypi3-64 ===
ERROR: ttf-takao different signature for task do_package_write_ipk.sigdata between tissot and raspberrypi3-64
NOTE: Starting bitbake server...
Hash for dependent task fontconfig/fontconfig_2.13.1.bb:do_packagedata changed from 96b1c46d82cc5e324700f930658af17cc29c3fd5311164fa4d0babc2e7613257 to 3e925fdfcf4a72b498215611b495a04ac95650924b0bddf13640724e8b7a7dd7
Unable to find matching sigdata for /home/jenkins/workspace/luneos-unstable/webos-ports/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.13.1.bb:do_packagedata with hashes 96b1c46d82cc5e324700f930658af17cc29c3fd5311164fa4d0babc2e7613257 or 3e925fdfcf4a72b498215611b495a04ac95650924b0bddf13640724e8b7a7dd7
ERROR: 1 errors found in /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/sstate-diff/1629372962/signatures.raspberrypi3-64.do_package_write_ipk.sigdata.log

Signed-off-by: Khem Raj <raj.khem@gmail.com>