crash: build bundled GDB with GNU C++17
The GDB 10.2 sources still rely on std::allocator::construct, which was
removed in C++20.

This causes the build to fail with errors such as:

default-init-alloc.h:52:12: error:
'construct' has not been declared in 'class std::allocator<...>'

Explicitly build the C++ sources with GNU C++17 to retain compatibility
with the bundled GDB sources.

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>