python3-lief: Update to tip of master branch
Fixes build issues with clang

In file included from TMPDIR/work/core2-32-yoe-linux/python3-lief/0.16.2/git/src/MachO/ChainedPointerAnalysis.cpp:19:
TMPDIR/work/core2-32-yoe-linux/python3-lief/0.16.2/git/include/LIEF/MachO/ChainedPointerAnalysis.hpp:390:17: error: static assertion failed due to requirement 'sizeof(LIEF::MachO::ChainedPointerAnalysis::union_pointer_t) == 16'
  390 |   static_assert(sizeof(union_pointer_t) == 16);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>