python3-mpv: Do not consider it if commercial license is not selected
It depends on mpv which depends on ffmpeg needing commercial in
LICENSE_FLAGS_ACCEPTED

Fixes
ERROR: Nothing PROVIDES 'ffmpeg' (but /srv/pokybuild/yocto-worker/meta-oe/build/meta-openembedded/meta-oe/recipes-multimedia/mplayer/mpv_0.40.0.bb DEPENDS on or otherwise requires it)
ffmpeg was skipped: Has a restricted license 'commercial' which is not listed in your LICENSE_FLAGS_ACCEPTED.
NOTE: Runtime target 'mpv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mpv', 'ffmpeg']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-mpv', 'mpv', 'ffmpeg']

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Jan Claußen <jan.claussen10@web.de>