python-prettytable: fix files permissions
Got this runtime error:

IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg-info/PKG-INFO'

After some investigation, it looks like the pypi package is the culprit
as almost all the files in the tar.gz are set to 600 instead of 644.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>