mpv: Link libatomic on riscv64
gcc uses __atomic_compare_exchange_1 which is not implemented for rv64

Fixes
video/out/vo_libmpv.c:186: undefined reference to `__atomic_compare_exchange_1'
collect2: error: ld returned 1 exit status

Signed-off-by: Khem Raj <raj.khem@gmail.com>