libcyusbserial: fix installed-vs-shipped QA issue with multilib
* testing ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR} existence
  doesn't really work in cross compilation and on some hosts was causing:

  ERROR: QA Issue: libcyusbserial: Files/directories were installed but not shipped in any package:
    /usr/lib/libcyusbserial.so.1
    /usr/lib/libcyusbserial.so
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  libcyusbserial: 2 installed and not shipped files. [installed-vs-shipped]

  with multilib using /usr/lib32 or /usr/lib64 when the same didn't
  exist on host.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>