grpc: fix protobuf-lite package config
protobuf-lite is a package, not recipe, so current code leads to
ERROR: Nothing PROVIDES 'protobuf-lite'

Moving it to 4th part (rdepends) is not needed as grpc links against it
so that rdependency is asutomatic.

Therefore protobuf-lite should be removed.

Note: for native, this packageconfig does not even compile and for
target it fails to link.

Signed-off-by: Peter Marko <peter.marko@siemens.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>