tinyalsa: fix installation libdir path to match multilibs
Fixes
ERROR: tinyalsa-1.1.1+gitAUTOINC+8449529c7e-r0 do_package: QA Issue: tinyalsa: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/libtinyalsa.a
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Andreas Müller <schnitzeltony@googlemail.com>
Acked-by: Andreas Müller <schnitzeltony@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit d9f3e6dbed8e5d96f2069280f0a566af89afb2fa)
Signed-off-by: Armin Kuster <akuster808@gmail.com>