xl2tpd: set MACHINE_ARCH, because it depends on kernel
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: xl2tpd different signature for task do_configure.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'linuxlinux-yocto_4.1.bb.do_populate_sysroot', 'pppppp_2.4.7.bb.do_populate_sysroot', 'update-rc.dupdate-rc.d_0.7.bb.do_populate_sysroot', 'update-rc.dupdate-rc.d_0.7.bb.do_populate_sysroot:virtual:native', 'xl2tpdxl2tpd_1.3.6.bb.do_patch']
to
['gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'linuxlinux-yocto_4.1.bb.do_populate_sysroot', 'pppppp_2.4.7.bb.do_populate_sysroot', 'update-rc.dupdate-rc.d_0.7.bb.do_populate_sysroot', 'update-rc.dupdate-rc.d_0.7.bb.do_populate_sysroot:virtual:native', 'xl2tpdxl2tpd_1.3.6.bb.do_patch']
openembedded-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb.do_populate_sysroot with hash 1a8aa7a50a6cf3ebf5401af43dd6bf3b
 changed to
openembedded-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb.do_populate_sysroot with hash 143d2686a37f592891fb2aa6fa9b752e
Hash for dependent task linuxlinux-yocto_4.1.bb.do_populate_sysroot changed from 1a8aa7a50a6cf3ebf5401af43dd6bf3b to 143d2686a37f592891fb2aa6fa9b752e

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>