softhsm: fix build with OpenSSL 4.0
do_compile fails with:

  OSSLUtil.cpp:188:46: error: invalid use of incomplete type
  'ASN1_PRINTABLESTRING' {aka 'struct asn1_string_st'}

Backport the upstream fix. It was written for a memory leak, but it
moves to the ASN1_STRING accessors, which is also what OpenSSL 4 needs.

Signed-off-by: Alper Ak <alperyasinak1@gmail.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>