plymouth: fix usrmerge
When usrmerge is enabled plymouth still tries to install to /bin and
/lib leading to the following build error:
ERROR: plymouth-git-r0 do_package: QA Issue: plymouth: Files/directories
were installed but not shipped in any package:
  /sbin/plymouthd
  /lib/libply.so.5
  /lib/libply.so
  /lib/libply.so.5.0.0
  /lib/libply-splash-core.so
  /lib/libply-splash-core.so.5.0.0
  /lib/libply-splash-core.so.5
  /bin/plymouth

There is a configuration flag --with-system-root-install which controls
where the binaries get installed. The flag is currently tied to the
systemd distro feature, however, this seems wrong.

Use the flag to control where binaries get installed depending on
whether usrmerge is used.

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>