librtorrent: Disable instrumentation on rv32
instrumentation code uses atomic ops on 64bit variables, which leads to build
failures on 32bit targets using libtorrent because of missing builtins on
riscv32/gcc

/usr/lib/libtorrent.so: undefined reference to `__sync_add_and_fetch_8'
/usr/lib/libtorrent.so: undefined reference to `__sync_fetch_and_and_8'

The developer added a "--disable-instrumentation" switch which skips the build
of the offending codepaths in libtorrent.

Signed-off-by: Khem Raj <raj.khem@gmail.com>