libpeas: this depends on gtk3+ add FEATURE CHECK
This has a dependancy on GTK3DISTROFEATURES so add the check

ERROR: Nothing PROVIDES 'gtk+3' (but /.../meta-openembedded/meta-oe/recipes-gnome/libpeas/libpeas_1.25.3.bb, /.../poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.36.1.bb DEPENDS on or otherwise requires it)
gtk+3 was skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>