meta-oe: fixup LAYERDEPENDS to include meta-python
meta-oe depends on meta-python, for mongodb recipe, since
5cf9a144ad16 (mongodb: Upgrade to 4.0.1 release)

Trying to run the yocto-check-layer script fails with:

ERROR: Nothing PROVIDES 'python-cheetah-native' (but /work/yocto/meta-openembedded/meta-oe/recipes-dbs/mongodb/mongodb_git.bb
DEPENDS on or otherwise requires it). Close matches:
  python3-git-native
  python-nose-native
  python-native
ERROR: Required build target 'meta-world-pkgdata' has no buildable
providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata',
'mongodb', 'python-cheetah-native']

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>