libgdata: fix compiling for 32-bit targets
When compiling for 32-bit targets, compilation fails with the following error:

| ../libgdata-0.18.1/demos/calendar/calendar-cli.c:47:22: error: passing argument 1 of 'gmtime' from incompatible pointer type [-Wincompatible-pointer-types]
|    47 |         tm = gmtime (&tv->tv_sec);

Upstream meanwhile has refactored the failing part in an untagged commit:
they have removed the usage of GTimeVal, since it has been deprecated.

Since it also solves the compilation issue, backport that patch.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>