fluentbit: Fix packaging in multilib env
Fixes
ERROR: fluentbit-0.12.19-r0 do_package: QA Issue: fluentbit: Files/directories were installed but not shipped in any package:
/usr/lib/libfluent-bit.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 99fe1dec83456100e0bc1c02581defa7aaf04a16)
Signed-off-by: Armin Kuster <akuster808@gmail.com>