websocketapp: Fix multilib build
Fixes

ERROR: websocketpp-0.8.1-r0 do_package: QA Issue: websocketpp: Files/directories were installed but not shipped in any package:
/usr/lib
/usr/lib/cmake
/usr/lib/cmake/websocketpp
/usr/lib/cmake/websocketpp/websocketpp-configVersion.cmake
/usr/lib/cmake/websocketpp/websocketpp-config.cmake

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit b1a85631279b8f04b38562f9cf076f4cc0561a71)
Signed-off-by: Armin Kuster <akuster808@gmail.com>