evolution-data-server-native: Use inherit_defer for native class
Since gnome classes are using it in core, they are now appearing after
native resulting in QA errors

ERROR: /mnt/b/yoe/master/sources/meta-openembedded/meta-gnome/recipes-gnome/evolution-data-server/evolution-data-server-native.bb: QA Issue: evolution-data-server-native: native/nativesdk class is not inherited last, this can result in unexpected behaviour. Classes inherited after native/nativesdk: pkgconfig.bbclass
siteconfig.bbclass siteinfo.bbclass autotools.bbclass [native-last]

Signed-off-by: Khem Raj <raj.khem@gmail.com>