imlib2: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/bin/imlib2-config conflicts between attempted installs of lib32-imlib2-bin-1.7.1-r0.armv7ahf_neon and imlib2-bin-1.7.1-r0.aarch64

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>