ledmon: fix building on 32-bit x86
Building the recipe on x86 platform fails with the following error:
| ../../git/src/utils.c: In function 'get_uint64':
| ../../git/src/utils.c:105:18: error: passing argument 1 of 'str_toul' from incompatible pointer type [-Wincompatible-pointer-types]
|   105 |         str_toul(&defval, p, NULL, 16);

Upstream has already changed this function to avoid overflow due to the
size difference in the pointer - this change backports that patch.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>