paprefs: add x11 to REQUIRED_DISTRO_FEATURES
* This doesn't build with any gtk3 DISTRO_FEATURES, without x11 in
  DISTRO_FEATURES gtk3+ doesn't provide gdkx.h and paprefs build fails with:
  http://errors.yoctoproject.org/Errors/Details/704195/

../paprefs-1.2/src/paprefs.cc:30:10: fatal error: gdk/gdkx.h: No such file or directory
   30 | #include <gdk/gdkx.h>
      |          ^~~~~~~~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>