python3-markdown: add logging and setuptools to RDEPENDS
Importing the markdown module causes standard ModuleNotFoundErrors
if the logging and pkg_resources modules are unavailable:

root@qemux86-64:~# python3
Python 3.8.2 (default, Apr 27 2020, 08:51:00)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.8/site-packages/markdown/_init_.py", line 25, in <module>
from .core import Markdown, markdown, markdownFromFile
File "/usr/lib64/python3.8/site-packages/markdown/core.py", line 27, in <module>
import logging
ModuleNotFoundError: No module named 'logging'

Signed-off-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>