open-vm-tools: move to meta-networking
* and make it skipped only when meta-filesystem is missing as well

* depends on libdnet from meta-networking and nothing in meta-oe depends on open-vm-tools

* update packagegroup-meta-oe to match this, without either of these layers packagegroup-meta-oe is currently failing with:

  ERROR: Nothing RPROVIDES 'open-vm-tools' (but meta-oe/recipes-core/packagegroups/packagegroup-meta-oe.bb RDEPENDS on or otherwise requires it)
  open-vm-tools was skipped: Requires meta-networking and meta-filesystems to be present.
  NOTE: Runtime target 'open-vm-tools' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['open-vm-tools']
  ERROR: Required build target 'packagegroup-meta-oe' has no buildable providers.
  Missing or unbuildable dependency chain was: ['packagegroup-meta-oe', 'open-vm-tools']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>