dvb-apps: Use tarball for SRC_URI and fix build on musl
Convert to using tarball for SRC_URI, this is only recipe in
meta-openembedded needing mercurial fetcher

Fix the stime replacement patch to fix type errors on time_t

| dvbdate.c:313:12: error: incompatible pointer to integer conversion assigning to 'time_t' (aka 'long') from 'time_t **' (aka 'long **') [-Wint-conversion]
|         ts.tv_sec = &new_time;
|                   ^ ~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>