iscsitarget: resolve build error with linux kernel 4.3 and above
1. test_bit was used to return true boolean value, if
   BIO_UPTODATE bit of bio->bi_flags is set. But the same
   job can be done by checking bio->bi_error, implemented in
   linux kernel 4.3 and above. If bio->bi_error is set, then
   it denotes error.

Ref: https://github.com/torvalds/linux/commit/4246a0b63bd8f56a1469b12eafeb875b1041a451

It solves below build error:
-- snip --
iscsitarget-1.4.20.3+svn502/kernel/block-io.c:40:19: error: 'BIO_UPTODATE' undeclared (first use in this function)
   error = test_bit(BIO_UPTODATE, &bio->bi_flags) ? error : -EIO;
-- CUT --

2. bio can always be filled to a maximum value of BIO_MAX_PAGES,
   so no need to check for min value for linux kernel 4.3 and above.

Ref: https://github.com/torvalds/linux/commit/b54ffb73cadcdcff9cc1ae0e11f502407e3e2e4c

It solves below build error:
-- snip --
iscsitarget-1.4.20.3+svn502/kernel/block-io.c:80:15: error: implicit declaration of function 'bio_get_nr_vecs' [-Werror=implicit-function-declaration]
    max_pages = bio_get_nr_vecs(bio_data->bdev);
-- CUT --

3. Remove unwanted explicit setting of CFLAGS and CC flags. Setting them in
   oe_runmake command, will override CFLAGS mentioned in iscsitarget Makefile
   and resulting in a below error:

-- snip --
 In file included from iscsid.c:38:0:
 iscsid.h:38:19: fatal error: iet_u.h: No such file or directory
 compilation terminated.
 In file included from conn.c:15:0:
 iscsid.h:38:19: fatal error: iet_u.h: No such file or directory
 compilation terminated.
-- CUT --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>