rrdtool: Upgrade to 1.7.1
Backport 3 patches to fix below error:
ERROR: rrdtool-1.7.1-r0 do_package: SYSTEMD_SERVICE_rrdcached value rrdcached.socket does not exist

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>